.\" Version: 1.2
.\"
.TH ocf_suse_SAPHanaController 7 "14 Oct 2025" "" "OCF resource agents"
.\"
.SH NAME
SAPHanaController \- Manages takeover between two SAP HANA databases with system replication.
.PP
.\"
.SH DESCRIPTION
.\"
\fBSAPHanaController\fP is an resource agent (RA) for SAP HANA databases. It
manages takeover for a SAP HANA database with system replication in an OCF
promotable clone configuration.
.PP
For details on using SAPHanaController in SAP HANA \fBscale-up\fR scenarios, please look into manual page
SAPHanaController-scale-up(7).
.PP
For details on using SAPHanaController SAP HANA \fBscale-out\fR scenarios, please look into manual page
SAPHanaController-scale-out(7).
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaController-scale-up\fP(7) , \fBSAPHanaController-scale-out\fP(7) ,
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR\fP(7) , \fBSAPHanaSR-ScaleOut\fP(7) ,
.br
https://documentation.suse.com/sbp/sap/
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2014 SUSE Linux Products GmbH, Germany.
.br
(c) 2015-2017 SUSE Linux GmbH, Germany.
.br
(c) 2018-2026 SUSE LLC
.br
The resource agent SAPHanaController comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
