.\" Version: 1.2 
.\"
.TH SAPHanaSR-angi-scenarios 7 "28 Oct 2024" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-angi-scenarios \- SAP HANA system replication scenarios.
.PP
.\"
.SH DESCRIPTION
.PP


.pp
Here's a simple table with boxes around every cell.
In the column specification, append
.b b
to make that item bold, which is typical for a
header.
.TS
tab(@) allbox center;
lb cb rb
l  c  r.
Left@Center@Right
one@two@three
four@five@six
seven@eight@nine
.TE
.pp
Here's a more complicated table that spans columns
and rows. Use
.b s
to span columns into each other, and
.b ^
to span rows into each other: (reference:
.i "ANSI X3.9-1978" ,
page 3-4s)
.TS
tab(@) allbox center;
c c s
^ c c
^ ^ c
^ ^ c
^ ^ c
^ ^ c
c s s.
Comment Lines@PROGRAM, FUNCTION, or SUBROUTINE
@FORMAT@IMPLICIT
@@Other Specification
@@DATA
@@Statement Function
@@Executable
END@@
.TE
.pp
And an updated version of the table with additional
spans. Note that the column specification at the top
has one row per line, so we can match up the rows we
want: (reference:
.i "ANSI X3.9-1978" ,
page 3-4)
.TS
tab(@) allbox center;
c c s s
^ c c c
^ ^ ^ c
^ ^ c c
^ ^ ^ c
c s s s.
Comment Lines@PROGRAM, FUNCTION, SUBROUTINE, or BLOCK DATA@@
@FORMAT and ENTRY@PARAMETER@IMPLICIT
@@@Other Specifications
@@DATA@Statement Functions
@@@Executable
END@@@
.TE



.TS
box center tab(:);
Lz  S | Rt
Ld| Cb| ^
^ | Rz  S.
left:r
l:center:
:right
.TE


.TS
center box tab(@);
cB | cB | cB
n | l | l.
Topology @ Scenario @
_
Scale-Up @ Perf-Opt @
Scale-Up @ Cost-Opt @
_
Scale-Out @ Perf-Opt @
.TE

.PP
.\"
.SH BUGS
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR\fP(7) \fBSAPHanaSR-ScaleOut\fP(7)
.PP
.\"
.SH AUTHORS
.PP
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2024 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
