.\" Version: 1.2
.\"
.TH SAPHanaSR 7 "10 Jan 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-angi \- SAP HANA SR - Advanced Next Generation Interface.
.PP
.\"
.SH DESCRIPTION
.\"
The SAPHanaSR-angi package provides resource agents (RA), HA/DR provider hook
scripts and tools for setting up and managing automation of SAP HANA system
replication (SR) in scale-up and scale-out setups.
.PP
The following SAP HANA SR scenarios are possible with SAPHanaSR-angi:
.RS 2
* scale-up performance-optimized (memory preload on secondary)
.br
* scale-up cost-optimized (e.g. with QA on secondary)
.br
* scale-up multi-tier or multi-target, 3rd site outside cluster
.br
* scale-up active/read-enabled
.br
* scale-up single-tenant or multi-tenant (MDC low isolation) for all the above
.br
* scale-up multiple independent HANA SR pairs (MCOS) in one cluster
.br
* scale-out performance-optimized with standby nodes
.br
* scale-out performance-optimized without standby nodes
.br
* scale-out multi-tier or multi-target, 3rd site outside cluster
.br
* scale-out active/read-enabled for two-node sites
.br
* scale-out single-tenant or multi-tenant (MDC low isolation) for all the above
.RE
.PP
See manual page SAPHanaSR-angi-scenarios(7) for details.
.PP
Note: Some tools from SAPHanaSR are shipped as -legacy with first versions of
SAPHanaSR-angi. This tools will be removed.
.PP
.\"
.SH REQUIREMENTS
.\"
Please find information on specific requirements of Linux HA scenarios for SAP HANA
SR scale-up and scale-out setups in the REQUIREMENTS section of SAPHanaSR(7) and
SAPHanaSR-ScaleOut(7). For the HA/DR provider hooks scripts details are providedin
their respective manual pages susHanaSR.py(7), susTkOver.py(7), susChkSrv.py(7),
susCostOpt.py(7) et al.
.PP
The SAPHanaSR-angi package is not compatible to SAPHanaSR and SAPHanaSR-ScaleOut.
Upgrading from that packages to SAPHanaSR-angi requires manual migration of at
least Linux cluster CIB attributes, sudoers permissions and HANA global.ini.
.PP
.\"
.SH BUGS
.\"
.\" TODO
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR\fP(7) , \fBSAPHanaSR-ScaleOut\fP(7) ,
\fBSAPHanaSR-angi-scenarios\fP(7) ,
\fBocf_suse_SAPHanaTopology\fP(7) , \fBocf_suse_SAPHanaController\fP(7) ,
\fBocf_heartbeat_IPaddr2\fP(7) ,
\fBSAPHanaSR_basic_cluster\fP(7) ,
\fBsusHanaSR.py\fP(7) , \fBsusHanaSrMultiTarget.py\fP(7) ,
\fBsusCostOpt.py\fP(7) , \fBsusTkOver.py\fP(7) , \fBsusChkSrv.py\fP (7) ,
\fBSAPHanaSR-showAttr\fP(8) ,
\fBntp.conf\fP(5) , \fBchrony.conf\fP(5) , \fBsystemctl\fP(1) ,
\fBstonith\fP(8) , \fBsbd\fP(8) , \fBstonith_sbd\fP(7) , \fBstonith_admin\fP(8) ,
\fBcrm\fP(8) , \fBcorosync.conf\fP(5) , \fBcrm_no_quorum_policy\fP(7) ,
\fBsaptune\fP(8) , \fBcs_show_hana_info\fP(8) , \fBsupportconfig\fP(8) ,
.br
https://documentation.suse.com/sbp/sap/ ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://www.suse.com/releasenotes/ ,
.br
http://scn.sap.com/community/hana-in-memory/blog/2014/04/04/fail-safe-operation-of-sap-hana-suse-extends-its-high-availability-solution ,
.br
http://scn.sap.com/docs/DOC-60334 ,
.br
http://scn.sap.com/community/hana-in-memory/blog/2015/12/14/sap-hana-sps-11-whats-new-ha-and-dr--by-the-sap-hana-academy ,
.br
https://wiki.scn.sap.com/wiki/display/ATopics/HOW+TO+SET+UP+SAPHanaSR+IN+THE+COST+OPTIMIZED+SAP+HANA+SR+SCENARIO+-+PART+I
.br
https://blogs.sap.com/2020/01/30/sap-hana-and-persistent-memory/
.PP
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2022-2025 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
