.\" Version: 1.001 
.\"
.TH SAPHanaSR-upgrade-to-angi-demo 8 "06 Mar 2024" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-upgrade-to-angi-demo \- How to upgrade from SAPHanaSR to SAPHanaSR-angi.
.PP
.\"
.SH SYNOPSIS
\fBSAPHanaSR-upgrade-to-angi-demo\fR [ --help | --version | --list | --check | --upgrade ]
.br
\fBSAPHanaSR-upgrade-to-angi-demo\fR --run \fIFUNCTION\fP [ \fIFUNCTION\fP [ ...  ]] 
.\"
.SH DESCRIPTION
.PP
SAPHanaSR-upgrade-to-angi-demo demonstrates how to upgrade from SAPHanaSR to
SAPHanaSR-angi. The script collects information from an Linux HA cluster with
SAPHanaSR. Based on that data it shows step by step the commands to upgrade the cluster. The running configuration is not changed. See also manual page
SAPHanaSR_upgrade_to_angi(7).
.PP
.B SAPHanaSR-upgrade-to-angi-demo is shipped as technology preview.
.PP
.\"
.SH OPTIONS
.TP 4
\fB --help\fP
show help.
.TP 4
\fB --version\fP
show version.
.TP 4
\fB --check\fP
do some baasic checks on configuration and status of Linux cluster.
.TP 4
\fB --list\fP
list SAPHanaSR-upgrade-to-angi-demo functions.
.TP 4
\fB --run \fP \fIFUNCTION\fP [ \fIFUNCTION\fP [ ... ]]
run given function(s).
.TP 4
\fB --upgrade\fP
show demo for upgrade from SAPHanaSR to SAPHanaSR-angi.
.\"
.SH EXAMPLES
.PP
\fB*\fP Example for checking sane state of cluster.
.PP
This steps should be performed before doing anything with the cluster, and after
something has been done. See also SAPHanaSR_upgrade_to_angi(7) and SAPHanaSR_maintenance_examples(7).
.PP
.RS 2
# cs_clusterstate -i
.br
# crm_mon -1r
.br
# crm configure show | grep cli-
.br
# SAPHanaSR-showAttr
.br
# cs_clusterstate -i
.br
# SAPHanaSR-upgrade-to-angi-demo --check
.RE
.PP
\fB*\fP Example for demonstrating an upgrade.
.PP
TODO
See also SAPHanaSR_upgrade_to_angi(7).
.PP
.RS 2
# SAPHanaSR-upgrade-to-angi-demo --upgrade
.RE
.PP
.\"
.SH FILES
.TP
/usr/share/SAPHanaSR-angi/samples/SAPHanaSR-upgrade-to-angi-demo
unsupported script for demonstrating the procedure on a test cluster
.TP
/etc/sudoers.d/SAPHanaSR
recommended place for sudo permissions of HADR provider hook scripts
.TP
/hana/shared/$SID/global/hdb/custom/config/global.ini
on-disk representation of HANA global system configuration

.PP
.\"
.SH REQUIREMENTS
.PP
* The initial configuration matches SUSE´s documented setup of the SAPHanaSR
scale-up performance optimised-scenario.
.br
* Linux cluster, HANA and system replication are in sane state before the
upgrade. All cluster nodes are online.
.br
* SAPHanaSR-upgrade-to-angi-demo could be run on test systems. It must not be
run on production systems.
.br
* For further requirements see manual page SAPHanaSR_upgrade_to_angi(7).
.PP
.\"
.SH BUGS
.br
In case of any problem, please use your favourite SAP support process to open a request for the component BC-OP-LNX-SUSE. Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.br
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR\fP(7) ,
\fBocf_suse_SAPHana\fP(7) , \fBocf_suse_SAPHanaController\fP(7) ,
\fBSAPHanaSR.py\fP(7) ,
\fBsusHanaSR.py\fP(7) , \fBSAPHanaSR_upgrade_to_angi\fP(7) ,
\fBSAPHanaSR_maintenance_examples\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBcrm\fP(8) , \fBcrm_mon\fP(8) , \fBcrm_attribute\fP(8) , \fBcibadmin\fP(8) ,
\fBcs_wait_for_idle\fP(8).
.br
https://documentation.suse.com/sbp/sap/ ,
.br
https://www.suse.com/c/tag/towardszerodowntime/
.PP
.\"
.SH AUTHORS
.br
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.br
(c) 2024 SUSE LLC
.br
SAPHanaSR-upgrade-to-angi-demo comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
