.\" Version: 0.163.1
.\"
.TH SAPHanaSR-replay-archive 8 "05 Aug 2019" "" "SAPHanaSR"
.\"
.SH SYNOPSYS
\fBSAPHanaSR-replay-archive\fR [ --help | --version ]
.br
\fBSAPHanaSR-replay-archive\fR CRM_REPORT_ARCHIVE
.\"
.SH DESCRIPTION
SAPHanaSR-replay-archive can be used to re-play SAPHanaSR status changes info
from a crm_report archive.
.br
Therefor it searches a given crm_report archive for pe-input files and shows
status information in historical order. Basically SAPHanaSR-showAttr is called
for each pe-input file.
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help.
.HP
\fB --version\fR
	show version.
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.TP
# SAPHanaSR-replay-archive hb_report-06-06-2019.tar.bz2
	replay SAPHanaSR-showAttr data from all pe-input files in hb_report-06-06-2019.tar.bz2 .
.TP
# SAPHanaSR-replay-archive hb_report-06-06-2019.tar.bz2 | grep ^global
	show system replication status history from an HANA scale-out cluster.
.TP
.\" # SAPHanaSR-replay-archive hb_report-08-05-2019.tar.bz2 | grep -A13 ^global SAPHanaSR-replay-archive.txt | awk '$1=="global"{print "@",$0}; $11=="SOK"||$11=="SFAIL"||$11=="SWAIT"||$11=="WAIT4PRIM"{print $11}' | tr -d "\\n" | tr "@" "\\n"
.\"	show system replication status history from an HANA scale-up cluster.
.TP
.\" # SAPHanaSR-showAttr hb_report-08-05-2019.tar.bz2 | grep -A13 ^global SAPHanaSR-replay-archive.txt | awk '$1=="global"{print "@",$0}; $2=="PROMOTED"{print $1,$2}' | tr -d "\\n" | tr "@" "\\n"
.\" show system replication primary from an HANA scale-up cluster.
.\"
.SH FILES
.TP
/usr/sbin/SAPHanaSR-replay-archive
        the program itself.
.TP
/usr/sbin/SAPHanaSR-showAttr
        the working horse.
.TP
<CRM_REPORT_ARCHIVE>-tmp/
	per call created working directory.
.TP
<CRM_REPORT_ARCHIVE>-tmp/hb_report_log/<NODE>/pengine/pe-input-<NUM>.bz2
	extracted pe-input files.
.TP
<CRM_REPORT_ARCHIVE>-tmp/hb_report_log/<NODE>/cib.xml
	extracted CIB file.
.\"
.SH BUGS
Feedback is welcome, please mail to feedback@suse.com.
.SH SEE ALSO
\fBSAPHanaSR\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBcrm_report\fP(8) , \fBcrm_simulate\fP(8)
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.\"
.SH COPYRIGHT
(c) 2019 SUSE LLC
.br
SAPHanaSR-replay-archive comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"

