.\" Version: 0.152.22
.\"
.TH SAPHanaSR-showAttr 8 "02 Feb 2017" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-showAttr \- Shows Linux cluster attributes for SAP HANA system replication.
.\"
.SH SYNOPSYS
\fBSAPHanaSR-showAttr\fR [ --help | --version ]
.br
\fBSAPHanaSR-showAttr\fR [ --sid=SID ] [ --ino=INO ] [ --sort=KEY ]
.\"
.SH DESCRIPTION
SAPHanaSR-showAttr shows Linux cluster attributes for SAP HANA system replication automation.
The overall system replication (SR) state is shown as well as the HANA state on each node. If the HANA srHook method srConnectionChanged() is configured, the
respective information is shown as well.
.PP
The output shows the following section:
.\" The output shows three sections:
.\" .TP
.\" Global section
.\" .br
.\" global (\fBGlobal\fP)
.\" .br
.\" primary replication site (\fBprim\fP)
.\" .br
.\" secondary replication site (\fBsec\fP)
.\" .br
.\" replication state of secondary site, indicated by systemReplicationStatus.py (\fBsec_sync_state\fP)
.\" .br
.\" replication channel state indicated by srConnectionChanged (\fBsrHook\fP)
.\" .TP
.\" Site section
.\" site name (\fBSite\fP)
.\" .br
.\" last primary timestamp (\fBlpt\fP)
.\" .br
.\" landscape synchronisation status (\fBlss\fP)
.\" .br
.\" current master nameserver for that site (\fBmns\fP)
.\" .br
.\" system replication role (\fBsrr\fP)
.\" .TP
Hosts section
.br
hostname (\fBHosts\fP)
.br
state of the Linux cluster resource (\fBclone_state\fP)
.br
actual and configured roles for HANA on that node (\fBroles\fP)
.br
actual master score on that node (\fBscore\fP)
.br
site where the host sits (\fBsite\fP)
.\" TODO sit ino sort
.\"
.SH OPTIONS
.HP
\fB --help\fR
        show help.
.HP
\fB --version\fR
        show version.
.HP
\fB --sid \fISID\fR[:\fIINO\fR]
.br
	use SAP system ID \fISID\fR. Should be autodetected, if there is only one SAP HANA instance installed on the local cluster node. The SAP system ID is a 3 alphanum string with a valid SAP system name like SLE, HAE, FH1, C11, or P42.
.br
	use SAP instance number \fINUM\fR. Should be autodetected, if there is only one SAP HANA instance installed on the local cluster node. The SAP instance number must be represented by a two digit numer like 00, 05 or 42. Some numbers ares not allowed, f.e. 98.
.HP
\fB --sort \fIFIELD\fR
.br
	sort Hosts section table by field. Allowed values: roles, site. The default sort is by hostnames.
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.TP
# SAPHanaSR-showAttr --sort roles
show all SAPHanaSR attributes in the cluster and sort host table output by roles
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-showAttr
	the program itself.
.TP
/usr/sap/hostctrl/exe/saphostctrl
	the SAP host control command.
.\"
.SH BUGS
Formatting and content of this script's output will change, since this script
is under development.
Feedback is welcome, please mail to feedback@suse.com.
.\"
.SH SEE ALSO
\fBocf_suse_SAPHanaController\fP(7) , \fBocf_suse_SAPHanaTopology\fP(7) ,
\fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR-monitor\fP(8) , \fBcibadmin\fP(8) , 
.br
https://www.suse.com/products/sles-for-sap/resource-library/sap-best-practices.html ,
.br
https://www.susecon.com/doc/2015/sessions/TUT19921.pdf ,
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.\"
.SH COPYRIGHT
(c) 2014 SUSE Linux Products GmbH, Germany.
.br
(c) 2015-2017 SUSE Linux GmbH, Germany.
.br
SAPHanaSR-showAttr comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
