.\" Version: 1.2 
.\"
.TH SAPHanaSR_multi-target 7 "12 Feb 2026" "" "SAPHanaSR-angi"
.\"
.SH NAME
. \"
SAPHanaSR_multi-target \- SAPHanaSR multi-target system replication scenarios.
.\"
.SH DESCRIPTION
.\"
.PP
.\" TODO
maximum one additional replication
.br
only on replication controlled by HA cluster
.br
third site often is used as Disaster Recovery (DR) site, larger distance away
.br
often replication mode is async
.PP
Common possible scenarios:
.TP
Scale-up perf-opt with multi-target replication
[ A <= B' ] -> C
.TP
Scale-up perf-opt with multi-tier replication (directed replication chain), sub-case of multi-target
[ A' => B ] -> C
.\" .TP
.\" TODO Scale-up cost-opt with multi-target replication
.\" [ "Q,A <= B' ] -> C
.TP
Scale-up perf-opt with multi-target replication and fourth site
[ A <= B' ] -> C => D
.TP
Scale-out perf-opt ERP-style with multi-target replication
[ Aa <= Bb' ] -> Cc
.TP
Scale-out perf-opt ERP-style with multi-target replication and fourth site
[ Aa <= Bb' ] -> Cc => Dd
.PP
Please refer to manual page SAPHanaSR-angi-scenarios(7) for the scenario notation.
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP Procedure for connecting a third site by replication to a cluster-controlled HANA pair.
.PP
.\" TODO
.PP
.RS 2
1. Collecting information and preparing sheet
.br
2. Setting up the third site
.br
3. Adding the register secondaries setting to the cluster-controlled HANA databases
.\" TODO without restart?
.br
4. Copying HANA secure keystore from current primary to third site
.br
5. Registering the third HANA database to the current primary
.\" TODO --online?
.br
6. Checking the new replication
.br
7. Checking if cluster takeover still works, and third site follows
.RE
.PP
\fB*\fP Procedure for connecting a fourth site by replication to a third site.
.PP
.\" TODO
.PP
.RS 2
1. Collecting information and preparing sheet
.br
2. Setting up the fourth site
.br
3. Copying HANA secure keystore from current primary to fourth site
.br
4. Backing up the third HANA database and enabling system replication
.br
5. Registering the fourth HANA database to the third
.br
6. Checking the new replication
.RE
.PP
\fB*\fP Entry in gobal.ini to register secondaries on takeover.
.PP
This entry is needed at all HANA nodes of the Linux clsuter to allow the 
SAPHanaController parameter AUTOMATED_REGISTER=true in multi-target environments.
The HANA has to be stopped before the files can be edited. Do not copy the file
between nodes. Please check SAP HANA documentation for details.
.PP
.R2 2
[system_replication]
.br
 ...
.br
register_secondaries_on_takeover = true
 ...
.RE
.PP
\fB*\fP Copying the HANA secure keystore from primary to third site.
.PP
Needs to be done before registering the third site.
Third site node is node3, SID is HA1.
.PP
.RS 2
# cd /usr/sap/HA1/SYS/global/security/rsecssfs
.br
# md5sum */*
.br
# rsync -va * node3:$PWD/
.br
# ssh node3 "md5sum $PWD/*/*"
.RE
.PP
\fB*\fP Registering third site as additional secondary to production primary.
.PP
Needs to be done at third site (master) node.
Third site is site3, production primary is node1, SID is HA1, instance number
is 00, replication mode is async, operation mode is logreplay.
.PP
.RS 2
# su - ha1adm
.br
~> HDB info
.br
~> hdbnsutil -sr_register --remoteHost=node1 --remoteInstance=00 \\
.br
 --replicationMode=async --operationMode=logreplay --name=site3 \\
.br
 --online
.br
~> hdbnsutil -sr_state
.RE
.PP
\fB*\fP Backing up third site HANA and enabling system replication.
.PP
Needs to be done at third (master) node before registering fourth site.
SID is HA1, instance numbr is 00, site name is site3.
.PP
.RS 2
# su - ha1adm
.br
~> hdbsql -i 00 -u SYSTEM -d SYSTEMDB \\
.br
 "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"
.br
~> hdbnsutil -sr_enable --name=site3
.br
~> hdbnsutil -sr_state
.RE
.PP
.\"
.SH FILES
.\"
.TP
/hana/shared/$SID/global/hdb/custom/config/global.ini
on-disk representation of HANA global system configuration.
.TP
/usr/sap/$SID/SYS/global/security/rsecssfs/
HANA database secure keystore directory.
.PP
.\"
.SH REQUIREMENTS
.\"
.PP
\fB*\fP Only one system replication between the two SAP HANA databases in the Linux
cluster. Maximum one system replication to an HANA database outside the Linux cluster.
.PP 
\fB*\fP The replication mode is either sync or syncmem for the controlled replication.
Replication mode async is not supported inside the Linux cluster.
.PP
See also the REQUIREMENTS section in manual pages SAPHanaSR(7) and susHanaSR.py(7). 
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-angi-scenarios\fP(7) , \fBSAPHanaSR\fP(7) , 
\fBsusHanaSR.py\fP(7) , \fBocf_suse_SAPHanaController\fP(7) ,
\fBha_related_acronyms\fP(7) ,
.PP
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
