.\" Version: 1.001
.\"
.TH SAPHanaSR-alert 7 "12 Jun 2024" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-alert \- Alert agent for cluster fencing alerts.
.PP
.\"
.SH DESCRIPTION
SAPHanaSR-alert can be used to react on Linux cluster fencing alerts.

The Linux cluster provides TODO

improves three use cases for HANA scale-out TODO
.br
- HA/DR provider hook script susChkSrv.py action_on_lost=fence
.br
- resource agent SAPHanaController ON_FAIL_ACTION=fence
.br
- resource agent SAPHanaFilesystem ON_FAIL_ACTION=fence
.PP

This alert agent will run on all Linux cluster nodes.
.PP
.\"
.SH SUPPORTED PARAMETERS
.PP
.\"
.PP
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.br
In addition log entries are written, which can be scanned by using a pattern
like "SAPHanaSR-alert".
.PP
.\"
.SH EXAMPLES
.PP
\fB*\fR Example configuration for the fencing alert handler.
.PP
TODO
.PP
alert fencing-1 "/usr/bin/SAPHanaSR-alert" select fencing
.PP
\fB*\fR Example for configuring the alert agent per crm.
.PP
Alternate way for configuring the aler agent.
.PP
# crm configure alert fencing-1 "/usr/bin/SAPHanaSR-alert" select fencing
.PP
\fB*\fR Example for showing all configured alert agents.
.PP
# crm configure show | grep -A1 alert
.PP
\fB*\fR Example for showing
.PP
# grep SAPHanaSR-alert /var/log/messages
.PP
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-alert
the alert agent
.TP
/run/crm/SAPHanaSR_site_cache
the internal cache for host TODO site
.PP
.\"
.SH REQUIREMENTS
1. Pacemaker 2.1 TODO or newer.
.PP
2. HANA scale-out performance-optimized scenario.
.PP
3. Only one SID controlled by the Linux cluster.
.PP
4. No other alert agent should be configured for the fencing alert.
.PP
5. The alert agent runtime almost completely depends on call-outs to OS and
Linux cluster.
.\"
.SH BUGS
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-angi\fP(7) ,
\fBocf_suse_SAPHanaController\fP(7) , \fBocf_suse_SAPHanaFilesystem\fP(7) ,
\fBsusChkSrv.py\fP (7) , \fBcrm\fP(8)
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.br
(c) 2024 SUSE LLC
.br
SAPHanaSR-alert comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
