.\" Version: 1.2 
.\"
.TH SAPHanaSR-ScaleOut-XSA 7 "26 Nov 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
SAPHanaSR-ScaleOut-XSA \- Automating SAP HANA system replication for standalone XSA setups.
.PP
.\"
.SH DESCRIPTION
.\"
This manual page provides information for setting up and managing automation of
SAP HANA system replication (SR) in scale-out setups with a standalone eXtended
application Services Advanced (XSA) server.
For other scale-out scenarios, please refer to SAPHanaSR-ScaleOut(7).
.PP
SAP HANA XSA provides a platform for the development and execution of micro-service
oriented applications.
.PP
The scale-out standalone XSA scenario consists of two nodes per site.
One node runs the HANA master namesever and an indexserver. The other node runs
an HANA nameserver slave and the standalone XSA server, but no indexserver.
.\" TODO roles  slave:slave:none:none
HANA system replication is set up between the two sites. In addition, the XSA
Filesystem Storage (fss) is shared across the sites.
.PP
\fBThe SUSE HA for SAP HANA SR scale-out standalone XSA scenario is a technology preview.\fP
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP Overview on setting up SAP HANA with standalone XSA and system replication.
.PP
The site2 will become primary in this example, site1 will become secondary.
.PP
install HANA with standalone XSA on site1 with node11 (master/worker) and node12 (xs_worker)
.br
install HANA with standalone XSA on site2 with node21 (master/worker) and node22 (xs_worker)
.br
export share with fss directory on NFS server
.br
prepare /etc/fstab on node12 and node22
.br
copy XSA ssfs keystore from site2 to site1
.PP
disable XSA, back-up XSA fss on node12
.br
change fss to NFS in xscontroller.ini on site1
.br
create mountpoint for fss share on node12
.br
mount fss share from NFS on node12
.br
restore XSA fss, enable XSA on node12
.br
stop HANA on site1
.PP
disable XSA, back-up XSA fss on node22
.br
change fss to NFS in xscontroller.ini on site2
.br
mount fss share from NFS on node22
.br
restore XSA fss, enable XSA on node22
.br
copy xscontroller.ini from site2 to site1
.PP
back-up HANA on node21
.br
enable HANA system replication on node11
.PP
register HANA site1 as secondary to node21
.br
start HANA on site1
.PP
\fB*\fP XSA fss entry in xscontroller.ini.
.PP
Example SID is HA1, directory is xsfss.
.PP
.RS 2
# cat /hana/shared/HA1/global/hdb/custom/config/xscontroller.ini
.br
 ...
.br
[fss]
.br
fss_storage_path = /hana/shared/HA1/xs/controller_data/xsfss 
.RE
.PP
\fB*\fP XSA fss entry in /etc/fstab.
.PP
Below is an fstab example for a shared filesystem holding the XSA fss. 
This fstab entry is needed on both XSA standalone nodes, not on the HANA
master nodes.
The filesystem is statically mounted on all HANA nodes of the cluster. The
correct mount options are depending on the NFS server. However, client-side write
caching has to be disabled in any case. The path has to match fss_storage_path
in xscontroller.ini. Since the fss directory is mounted below /hana/shared, which
also comes from outside, the fss entry should follow later.
.PP
.RS 2
nfs1:/s/ha1/xsfss /hana/shared/HA1/xs/controller_data/xsfss nfs4 rw,noac,sync,default 0 0
.RE
.PP
Note: The NFS share might be monitored, but not mounted/umounted by the HA cluster.
See ocf_suse_SAPHanaFilesystem(7) for details.
.RE
.PP
\fB*\fP Creating local mountpoint for XSA fss from remote NFS.
.PP
As above, SID is HA1 and directory is xsfss.
.PP
.RS 2
# mkdir /hana/shared/HA1/xs/controller_data/xsfss
.br
# chown ha1adm:sapsys /hana/shared/HA1/xs/controller_data/xsfss
.RE
.PP
\fB*\fP Copying the XSA ssfs keystore from primary site to secondary.
.PP
Primary site is site2, secondary site is site1, SID is HA1.
.PP
.RS 2
# cd hana/shared/HA1/global/xsa/security/
.br
# md5sum ssfs/*/*
.br
# rsync -va ssfs node11:$PWD/ 
.br
# ssh node11 "md5sum $PWD/ssfs/*/*"
.RE
.PP
\fB*\fP Disabling XSA and backing up the fss.
.PP
This needs to be done at both sites before changing the fss from local to NFS.
.PP
.RS 2
# su - ha1adm -c "XSA disable; XSA backup-fss"
.RE
.PP
\fB*\fP Restoring the fss and enabling XSA.
.PP
This needs to be done at both sites after the fss has been changed from local to
NFS.
.br
Make sure not both active XSA sites will access the shared fss directory at the
same time.
.PP
.RS 2
# su - ha1adm -c "XSA restore-fss; XSA enable"
.RE
.PP
.RS 2
# scp /hana/shared/HA1/global/hdb/custom/config/xscontroller.ini node11:/hana/shared/HA1/global/hdb/custom/config/
.RE
.PP
\fB*\fP Stopping HANA, including XSA.
.PP
This needs to be done at the site that should become secondary, before the fss
at the other site is changed from local to NFS.
.br
SID is HA1, instance number is 00.
.PP
.RS 2
# su - ha1adm
.br
~> sapcontrol -nr 00 -function StopSystem
.br
.\" TODO 30 60?
~> sapcontrol -nr 00 -function WaitforStopped 30 60
.br
~> sapcontrol -nr 00 -function GetSystemInstanceList
.RE
.PP
\fB*\fP Copying xscontroller.ini from primary to secondary site.
.PP
SID is HA1, secondary site XSA node is node11.
.br
Make sure XSA at secondary site is stopped before copying.
.PP
.RS 2
# scp /hana/shared/HA1/global/hdb/custom/config/xscontroller.ini node11:/hana/shared/HA1/global/hdb/custom/config/
.RE
.PP
\fB*\fP Backing up HANA and enabling system replication as primary site.
.PP
Primary site is site2, instance number is 00.
.PP
.RS 2
# su - ha1adm
.br
~> hdbsql -i 00 -u SYSTEM -d SYSTEMDB \\
.br
 "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"
.br
~> hdbnsutil -sr_enable --name=site2 
.RE
.PP
\fB*\fP Registering and starting HANA as secondary site.
.PP
Secondary site is site1, primary master is node21, instance number is 00.
Needs primary site up and running.
.PP
.RS 2
# su - ha1adm
.br
~> hdbnsutil -sr_register --name=site1 \\
.br
 --remoteHost=node21 --remoteInstance=00 \\
.br
 --replicationMode=sync --operationMode=logreplay
.br
~> sapcontrol -nr 00 -function StartSystem
.RE
.PP
\fB*\fP IPaddr2 resource for primary XSA.
.PP
Example SID is HA1, instance number is 00, IP address is 192.168.178.188.
.br
The shown location constraint works for setups with two nodes per site.
.PP
.RS 2
primitive rsc_ip_HA1_XSA00 IPaddr2 \\
.br
 op monitor interval=10s timeout=20s \\
.br
 params ip=192.168.178.188
.PP
location loc_ip_HA1_XSA00 \\
.br
 rsc_ip_HA1_XSA00 \\
.br
 rule 2000: master-rsc_SAPHanaCon_HA1_HDB00 eq 101
.PP
.RE
.PP
.\" .PP
.\" # sudo ha1adm
.\" ~> XSA ...
.\"
.\" ERROR: Authentication failed while trying to access the database 'HA1' as user 'SYS_XS_RUNTIME'
.PP
.\"
.SH FILES
.\"
.TP
/hana/shared/<SID>/global/hdb/custom/config/xscontroller.ini
XSA controller configuration.
.TP
/hana/shared/<SID>/xs/controller_data/fss/
default Filesystem Storage directory.
.TP
/etc/passwd , /etc/groups
local users and groups definition files.
.TP
/etc/fstab
static information about the filesystems.
.PP
.\"
.SH REQUIREMENTS
.\"
\fB*\fP Currently only two nodes per site are supported. One HANA master/worker and
one standalone XSA worker.
.PP
\fB*\fP The SAP HANA XSA service is installed for hostname based routing. This needs
DNS wildcard support at DNS server side.
.PP
Both sites are using the same XSA default domain and api url. 
.PP
\fB*\fP The XSA service IP address is configured as cluster resource and is moved
together with the primary XSA.
.PP
\fB*\fP Filesystem Storage (fss) is configured identically on both sites.
.PP
\fB*\fP A highly available NFS service provides the shared XSA fss directory
across sites.
.PP
\fB*\fP Linux user <sid>adm has same UID and GIDs on all cluster nodes.
.PP
\fB*\fP Linux user <sid>adm has sudo permission ALL for Linux users <sid>xsa and
sap<sid>xsa.
.PP
\fB*\fP The XSA keystore (ssfs) is copied from primary to secondary site.
.PP
\fB*\fP SAP HANA host auto-failover is not supported.
.PP
\fB*\fP Multi-target or multi-tier system replication is not supported.
.PP
\fB*\fP SAPHanaController relies on HANA landscape status.  
.PP
\fB*\fP For requirements of the overall scale-out setup, see also the REQUIREMENTS
section in SAPHanaSR-ScaleOut(7).
.PP
\fB*\fP For requirements of SAP HANA XSA, please refer to the SAP product documentation.
.PP
\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-ScaleOut\fP(7) ,
\fBSAPHanaSR-angi-scenarios\fP(7) , \fBocf_suse_SAPHanaFilesystem\fP(7) ,
\fBfstab\fP(5) , \fBnfs\fP(5) ,
.br
https://help.sap.com/docs/SAP_HANA_PLATFORM/6b94445c94ae495c83a19646e7c3fd56/5bc11f2ca7744bfd9d23d09e5b616433.html?version=2.0.07 ,
.br
https://help.sap.com/docs/SAP_HANA_PLATFORM/6b94445c94ae495c83a19646e7c3fd56/99306be18a1f493b990cf9d8d90cd922.html?version=2.0.07 ,
.br
1999880 - FAQ: SAP HANA System Replication
.br
2183363 - Configuration of SAP HANA internal network
.br
2243019 - Providing SSL certificates for domains defined in SAP HANA extended application services, advanced model
.br
2243156 - Secure user setup for SAP HANA extended application services, advanced model
.br
2245631 - Domains and routing configuration for SAP HANA extended application services, advanced model
.br
2303772 - SAP HANA XS Advanced Model SPS12 Release Note
.br
2300936 - Failover & High Availability with SAP HANA extended application services, advanced model
.br
2300937 - Backup and restore for SAP HANA extended application services, advanced model then notice XSA can't start up with error:
.br
2300943 - Enabling JDBC SSL encryption for SAP HANA extended application services, advanced model
.br
2507070 - 
.br
2509043 -
.br
2511224 - How to activate a XSA technical user
.br
2564474 - Installation of SAP HANA XS Advanced Runtime fails with error "Assigning Additional Roles to the Local Host failed".
.br
2596466 - FAQ: SAP HANA XS Advanced Information published on SAP
.br
2741459 - VA32 dump: DBSQL_DUPLICATE_KEY_ERROR
.br
2749450 - XSA technical user is frequently locked - authentication failed
.br
2752384 - HANA XS Advanced does not start - Unable to read the SID from the SL config store - authentication failed
.br
2866031 - 
.br
3014176 -
.br
3114270 - How to change the port used by existing application on XSA(XS advanced)
.br
3224631 - Hana is unavailable with message: "process is terminating, because lockfile '/usr/sap/.../../../lock/hdbindexserver@....pid' is missing/wrong."
.br
3234663 - XSA can't start up after system refresh due to error "Unable to locate XSA persistence within tenant db '<DB name>'"
.br
3335637 - Installation of SAP HANA XS Advanced Runtime stucks in adding the role xs_worker
.br
3449644 - Not able to change the XSA default_domain with xscontroller.ini
.PP
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2025 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
