.\" Version: 0.155.0
.\"
.TH SAPHanaSR_maintenance_examples 7 "12 Feb 2021" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR_maintenance_examples \- maintenance examples for SAPHana and SAPHanaController.
.PP
.\"
.SH DESCRIPTION
.PP
Please see also the REQUIREMENTS section below.
.RE
.PP
.\"
.SH EXAMPLES
.PP
* Initiate an administrative takeover of the HANA primary from one node to the other one.
If the cluster should also register the former primary as secondary, AUTOMATED_REGISTER="true" is needed. Before the takeover will be initiated, the status of the Linux cluster and the HANA system replication has to be checked. The takeover should only be initiated as forced migration. After takeover of the primary has been finished, the migration rule has to be deleted. If AUTOMATED_REGISTER="true" is set, finally the former primary will be registred as secondary, once the migration rule has been deleted. The below example works on SLE-HA 12 and 15. Former versions used "migrate" instead of "move" and "unmigrate" instead of "clear".
.PP
.RS 2 
# cs_clusterstate -i
.br
# SAPHanaSR-showAttr
.br
# crm configure show | grep cli-
.br
# crm resource move msl_SAPHana_SLE_HDB10 force
.br
# cs_clusterstate -i
.br
# SAPHanaSR-showAttr
.br
# crm resource clear msl_SAPHana_SLE_HDB10
.br
# SAPHanaSR-showAttr
.RE
.PP
* Manually start the HANA primary if only one node is available. This might be necessary in case the cluster could not detect the status of both nodes.
.PP
.RS 2
1. Start the cluster on both nodes.
.br
2. Wait and check for cluster is running, and in status idle.
.br
3. Become sidadm, and start HANA manually.
.br
4. Wait and check for HANA is running.
.br
5. In case the cluster does not promote the HANA to primary, instruct the cluster to migrate the IP adress to that node.
.br
6. Wait and check for HANA has been promoted to primary by the cluster.
.br
7. Remove the migration rule from the IP address.
.br
8. Check if cluster is in status idle.
.br
9. You are done, for now.
.br
10. Please bring back the other node and register that HANA as soon as possible. If the HANA primary stays alone for too long, the log area will fill up.
.RE
.PP
.\"
* Overview on maintenance procedure for HANA, the Linux cluster remains running.
.PP
.RS 2
1. Set the Linux cluster into maintenance mode (crm configure property maintenance-mode=true)
.br
2. Perform the HANA maintenance, e.g. update to latest SPS
.br
3. Set the SAPHanaController master/slave resource to unmanaged (crm resource unmanage <resource>)
.br
4. Set the Linux cluster back into ready mode (crm configure property maintenance-mode=false)
.br
5. Cleanup the SAPHanaController master/slave resource (crm resource cleanup <resource> node <node>)
.br
6. Set the SAPHanaController master/slave resource back to managed (crm resource manage <resource>)
.br
7. Check if everything looks fine (crm_mon -1r, cs_clusterstate -i, crm configure show | grep cli-,
 SAPHanaSR-showAttr).
.PP
.RE
Note: The YaST module hana_updater does something similar, combined with an
administrative takeover.
.PP
.\"
.SH FILES
.br
.PP
.\"
.SH REQUIREMENTS
.br
For the current version of the resource agents that come with the software packages SAPHanaSR and SAPHanaSR-ScaleOut,
the support is limited to the scenarios and parameters described in the respective manual pages SAPHanaSR(7) and
SAPHanaSR-ScaleOut(7).
.PP
.\"
.SH BUGS
.\" TODO
In case of any problem, please use your favourite SAP support process to open a request for the component BC-OP-LNX-SUSE. Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.br
\fBocf_suse_SAPHanaTopology\fP(7) , \fBocf_suse_SAPHana\fP(7) , \fBocf_suse_SAPHanaController\fP(7) ,
\fBSAPHanaSR-monitor\fP(8) , \fBSAPHanaSR-showAttr\fP(8) , \fBSAPHanaSR\fP(7) , \fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR.py\fP(7) ,
\fBcs_clusterstate\fP(8) ,
\fBcrm\fP(8) , \fBcrm_simulate\fP(8) , \fBcrm_mon\fP(8) ,
.br
https://www.suse.com/products/sles-for-sap/resource-library/sap-best-practices.html ,
https://www.suse.com/media/presentation/TUT90846_towards_zero_downtime%20_how_to_maintain_sap_hana_system_replication_clusters.pdf
.br
.PP
.\"
.SH AUTHORS
.br
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2017-2018 SUSE Linux GmbH, Germany.
.br
(c) 2019-2021 SUSE LLC
.br
This maintenance examples are coming with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
