.\" Version: 1.2 
.\"
.TH SAPHanaSR_multi-target 7 "12 Feb 2026" "" "SAPHanaSR-angi"
.\"
.SH NAME
. \"
SAPHanaSR_multi-target \- SAPHanaSR multi-target system replication scenarios.
.\"
.SH DESCRIPTION
.\"
If more than one HANA secondary site is connected by system replication to one
same primary, it is HANA multi-target system replication.
.\" TODO multi-tier
.PP
In any case, only two HANA sites, connected with one system replication, are
controlled by one Linux cluster.
A third HANA site, outside the cluster, might be connected by a second system
replication to one of the cluster sites.
And to that third site, a fourth one might be connected.
So, common possible scenarios are:
.TP
Scale-up perf-opt with multi-target replication
[ A <= B' ] -> C
.TP
Scale-up perf-opt with multi-tier replication (directed replication chain), sub-case of multi-target
[ A' => B ] -> C
.\" .TP
.\" TODO Scale-up cost-opt with multi-target replication
.\" [ "Q,A <= B' ] -> C
.TP
Scale-up perf-opt with multi-target replication and fourth site
[ A <= B' ] -> C => D
.TP
Scale-out perf-opt ERP-style with multi-target replication
[ Aa <= 'Bb ] -> Cc
.TP
Scale-out perf-opt ERP-style with multi-target replication and fourth site
[ Aa <= 'Bb ] -> Cc => Dd
.PP
Please refer to manual page SAPHanaSR-angi-scenarios(7) for the scenario notation.
.PP
The third site often is used as Disaster Recovery (DR) site, a longer distance
away. So the replication mode might be async. The decision and procedure for takeover
in DR case have to be prepared carefully and should be trained on regular base.  
.PP
Another case is a temporary replication, e.g. for filling test databases or performing
an upgrade. 
.PP
The Linux cluster recognises the status of the second replication by HANA HA/DR
provider hook event srConnectionChanged() on the primary node. See susChkSrv.py(7)
for details. The third replication link is invisible for the Linux cluster.
However, it is shown by systemReplicationStatus.py at the primary site. 
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP Procedure for connecting a third site by replication to a cluster-controlled HANA pair.
.PP
.\" TODO
Details on how to perform the steps can be found in examples below.
.PP
.RS 2
1. Collect information and prepare parameter sheet.
.br
2. Set up the third site.
.br
3. Add the register secondaries setting to the cluster-controlled HANA databases.
.\" TODO without restart?
.br
4. Copy HANA secure keystore from current primary to third site.
.br
5. Register the third HANA database to the current primary.
.\" TODO --online?
.br
6. Check the new replication.
.br
7. Check if cluster takeover still works, and third site follows.
.RE
.PP
\fB*\fP Procedure for connecting a fourth site by replication to a third site.
.PP
.\" TODO
Details on how to perform the steps can be found in examples below.
.PP
.RS 2
1. Collect information and prepare parameter sheet.
.br
2. Set up the fourth site.
.br
3. Copy HANA secure keystore from current primary to fourth site.
.br
4. Back up the third HANA database and enable system replication.
.br
5. Register the fourth HANA database to the third.
.br
6. Check the new replication.
.RE
.PP
\fB*\fP Procedure for disconnecting a temporarily connected third site while primary is available.
.PP
.\" TODO
Details on how to perform the steps can be found below.
.PP
.RS 2
1. Collect information and prepare parameter sheet.
.br
2. Disable system replication at third site.
.br 
3. Remove orphaned attributes from CIB.
.br
4. Check if cluster-controlled replication still works.
.RE
.PP
\fB*\fP Procedure for taking over to third site in DR case.
.PP
.\" TODO
Details on how to perform the steps can be found below.
.br
Note: Understand the impact before trying.
.PP
.RS 2
1. Make sure both sites of the Linux cluster are not running.
.br
2. Take decision for takeover.
.br
3. Disable system replication at third site.
.br
4. Activate IP adress at third node.
.\" TODO
.RE
.PP
\fB*\fP Procedure for taking back from third site to cluster.
.PP
.\" TODO
Details on how to perform the steps can be found below.
.br
Note: Understand the impact before trying.
.PP
.RS 2
.\" TODO
.RE
.PP
\fB*\fP Entry in gobal.ini to register secondaries on takeover.
.PP
This entry is needed at all HANA nodes of the Linux clsuter to allow the 
SAPHanaController parameter AUTOMATED_REGISTER=true in multi-target environments.
The HANA has to be stopped before the files can be edited. Do not copy the file
between nodes. Please check SAP HANA documentation for details.
.PP
.RS 2
[system_replication]
.br
 ...
.br
register_secondaries_on_takeover = true
 ...
.RE
.PP
\fB*\fP Copying the HANA secure keystore from primary to third site.
.PP
Needs to be done before registering the third site.
Third site node is node3, SID is HA1.
.PP
.RS 2
# cd /usr/sap/HA1/SYS/global/security/rsecssfs
.br
# md5sum */*
.br
# rsync -va * node3:$PWD/
.br
# ssh node3 "md5sum $PWD/*/*"
.RE
.PP
\fB*\fP Registering third site as additional secondary to production primary.
.PP
Needs to be done at third site (master) node.
Third site is site3, production primary is node1, SID is HA1, instance number
is 00, replication mode is async, operation mode is logreplay.
.PP
.RS 2
# su - ha1adm
.br
~> HDB info
.br
~> hdbnsutil -sr_register --remoteHost=node1 --remoteInstance=00 \\
.br
 --replicationMode=async --operationMode=logreplay --name=site3 \\
.br
 --online
.br
~> hdbnsutil -sr_state
.RE
.PP
\fB*\fP Checking srHook attribute for third site.
.PP
Could be done at any cluster node once a tihrd site has been connected.
The susHanaSR.py HA/DR provider hook script of the cluster-controlled HANA databases
will detect the outer system replication and write a related srHook attribute into
CIB. The srHook attributes have to be distinguished by site names.
The two production sites are site1 and site2 the third (e.g. DR) site is site3.
See also susHanaSR.py(7) and SAPHanaSR-showAttr(8).
.PP
.RS 2
# crm configure show SAPHanaSR | \\
.br 
 grep -e _srHook_site1= -e _srHook_site2= -e _srHook_site3=
.br
# SAPHanaSR-showAttr
.RE
.PP
\fB*\fP Backing up third site HANA and enabling system replication.
.PP
Needs to be done at third site (master) node before registering fourth site.
SID is HA1, instance numbr is 00, site name is site3.
.PP
.RS 2
# su - ha1adm
.br
~> hdbsql -i 00 -u SYSTEM -d SYSTEMDB \\
.br
 "BACKUP DATA FOR FULL SYSTEM USING FILE ('backup')"
.br
~> hdbnsutil -sr_enable --name=site3
.br
~> hdbnsutil -sr_state
.RE
.PP
\fB*\fP Disabling system replication at third site while source is available.
.PP
.\" TODO
replication source needs to be up and running
.PP
.RS 2
# su - ha1adm
.br
~> hdbnsutil -sr_state
.br
~> hdbnsutil -sr_disable
.br
~> hdbnsutil -sr_state
.RE
.PP
\fB*\fP Disabling system replication at third site when source is not available.
.PP
.\" TODO
.PP
.RS 2
# su - ha1adm
.br
~> hdbnsutil -sr_state
.br
~> hdbnsutil ...
.br
~> hdbnsutil -sr_state
.RE
.PP
\fB*\fP Removing orphaned srHook attribute from CIB.
.PP
Might be done at any cluster node once once a temporary replication has been
finally disabled. To be removed srHook´s SID is ICE, site is BERG.
.br
Note: Understand the impact before trying.
.PP
.RS 2
# crm configure show SAPHanaSR | grep _srHook_BERG=
.br
# crm_attribute -n hana_ice_site_srHook_BERG -t crm_config \\
.br
 -s SAPHanaSR --delete
.br
# crm configure show SAPHanaSR | grep _srHook_BERG=
.RE
.PP
\fB*\fP Checking status of all system replication connections.
.PP
Could be done at primary site (master) node. SID is HA1.
See also SAPHanaSR_maintenance_examples(7) and susHanaSR.py(7).
.PP
.RS 2
# su - ha1adm
.br
~> cdpy; python3 ./systemReplicationStatus.py; echo RC:$?
.RE
.PP
.\"
.SH FILES
.\"
.TP
/hana/shared/$SID/global/hdb/custom/config/global.ini
on-disk representation of HANA global system configuration.
.TP
/usr/sap/$SID/SYS/global/security/rsecssfs/
HANA database secure keystore directory.
.PP
.\"
.SH REQUIREMENTS
.\"
\fB*\fP Only one system replication between the two SAP HANA databases in the Linux
cluster. Maximum one system replication to an HANA database outside the Linux cluster.
.PP 
\fB*\fP The replication mode is either sync or syncmem for the controlled replication.
Replication mode async is not supported inside the Linux cluster.
.PP
\fB*\fP Once an HANA system replication site is known to the Linux cluster, that
exact site name has to be used whenever the site is registered manually. At any
time only one site is configured as primary replication source.
.PP
\fB*\fP No Multi-SID scenario.
.PP
\fB*\fP Sufficient disk space for transaction logs and log backup at each potential
replication source. Housekeeping might also help.
.PP
\fB*\fP The Linux cluster has no control over HANA system replication and HANA
landscape status outside the cluster.
.PP
\fB*\fP If the third site is used as DR site, decision and procedure for takeover
are in customer´s responsibility.
.PP
\fB*\fP Any manual procedure has to be tested, documented and trained before applied
on production systems.
.PP
See also the REQUIREMENTS section in manual pages SAPHanaSR(7) and susHanaSR.py(7). 
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-angi-scenarios\fP(7) , \fBSAPHanaSR\fP(7) , 
\fBsusHanaSR.py\fP(7) , \fBocf_suse_SAPHanaController\fP(7) ,
\fBha_related_acronyms\fP(7) ,
.PP
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
