.\" Version: 0.155.0
.\"
.TH SAPHanaSR-hookHelper 8 "27 May 2022" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-hookHelper - TODO
.\"
.SH SYNOPSIS
\fBSAPHanaSR-hookHelper\fR [ --help | --version ]
.br
\fBSAPHanaSR-hookHelper\fR TODO
.\"
.SH DESCRIPTION
\fBSAPHanaSR-hookHelper\fR TODO
.\"
.SH OPTIONS
.TP 4
\fB --help\fR
show help
.TP 4
\fB --version\fR
show script version
.TP 4
TODO
.TP
\fB --sid=\fISID\fR
use SID of the SAP system
.\"
.SH SUPPORTED PARAMETERS
.TP
TODO
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.SH EXAMPLES 
.\"
.SH FILES
.TP 4
/usr/sbin/SAPHanaSR-hookHelper
the program itself
.TP 4
/usr/share/SAPHanaSR/susTkOver.py
.TP 4
/etc/sudoers, /etc/sudoers.d/SAPHanaSR
the sudo permissions configuration
.\"
.SH BUGS
\fB*\fR Command line options of this script will change, since this script is under development. This script is not intended to be called outside HA/DR provider hook scripts.
.PP
\fB*\fR In case of any problem, please use your favourite SAP support process to
open a request for the component BC-OP-LNX-SUSE. Please report any other feedback and suggestions to feedback@suse.com.
.\"
.SH SEE ALSO
\fBSAPHanaSR\fP(7) , \fBSAPHanaSR-ScaleOut\fP(7) , 
\fBSAPHanaSR.py\fP(7) , \fBSAPHanaSrMultiTarget.py\fP(7) ,
\fBsusTkOver.py\fP(7) ,
\fBocf_suse_SAPHanaTopology\fP(7) , \fBocf_suse_SAPHana\fP(7) ,
\fBocf_suse_SAPHanaController\fP(7) ,
\fBSAPHanaSR-monitor\fP(8) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBcrm_attribute\fP(8) , \fBsudo\fP(8) , \fBsudoers\fP(5), 
.br
https://documentation.suse.com/sbp/all/?context=sles-sap
.\"
.SH AUTHORS
A.Briel, F.Herschel, L.Pinne
.\"
.SH COPYRIGHT
(c) 2022 SUSE LLC
.br
SAPHanaSR-hookHelper comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
