.\" Version: 0.154.0
.\"
.TH SAPHanaSR-monitor 8 "11 Sep 2019" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-monitor \- Display status of SAP HANA system replication automation (SAPHanaSR).
.\"
.SH SYNOPSYS
\fBSAPHanaSR-monitor\fR [ --help | --version ]
.br
\fBSAPHanaSR-monitor \fIOPTION VALUE\fR
.\"
.SH DESCRIPTION
\fBSAPHanaSR-monitor\fP displays the status of SAP HANA system replication (SAPHanaSR).
The overall system replication (SR) state is shown in an summarized manner.
.\" TODO 
.\"
.SH OPTIONS
.HP
\fB --help\fR
        show help.
.HP
\fB --version\fR
        show version.
.HP
\fB --cont\fR [ yes | no ]
.br
	repeat or run once, default is no.
.HP
\fB --format\fR [ txt | html ]
.br
	output format text or HTML, default is text.
.HP
\fB --intervall \fISEC\fR
.br
	repeat with intervall of \fISEC\fR seconds, default is 10 seconds.
.HP
\fB --nodes \fINUM\fR
.br
	number of nodes which should be in the cluster. Usually detected automatically.
.HP
\fB --out \fIFILE\fR
.br
	use output file \fIFILE\fR, default is /srv/www/hawk/public/SAPHanaSR/index.html.
    The directory is not created by the package.
.HP
\fB --sid \fISID[:INO]\fR
.br
	use SAP system ID \fISID\fR and optional SAP instance number \fIINO\fR.
    Could be used multiple times.
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.TP
# SAPHanaSR-monitor
show status of SAP HANA system replication one time.
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-monitor
	the program itself.
.TP
/usr/lib/SAPHanaSRTools.pm
	function libraries.
.TP
/srv/www/hawk/public/SAPHanaSR/index.html
	default path for output web page.
.TP
/var/log/messages
	the log with messages from OCF resource agents.
.\"
.SH BUGS
Formatting and content of this script's output will change, since this
script is under development.
Feedback is welcome, please mail to feedback@suse.com.
.\"
.SH SEE ALSO
\fBocf_suse_SAPHana\fP(7) , \fBocf_suse_SAPHanaTopology\fP(7) ,
\fBSAPHanaSR-showAttr\fP(8) , \fBcibadmin\fP(8) , 
.br
https://www.suse.com/products/sles-for-sap/resource-library/sap-best-practices.html ,
.br
http://scn.sap.com/community/hana-in-memory/blog/2014/04/04/fail-safe-operation-of-sap-hana-suse-extends-its-high-availability-solution
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.\"
.SH COPYRIGHT
(c) 2014 SUSE Linux Products GmbH, Germany.
.br
(c) 2015-2017 SUSE Linux GmbH, Germany.
.br
(c) 2018-2019 SUSE LLC.
.br
SAPHanaSR-monitor comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
