.\" Version: 1.2 
.\"
.TH SAPHanaSR-replay-archive 8 "24 Jul 2025" "" "SAPHanaSR"
.\"
.SH SYNOPSIS
.\"
\fBSAPHanaSR-replay-archive\fR [ --help | --version ]
.br
\fBSAPHanaSR-replay-archive\fR --sid \fISID\fR --cib \fICIB\fR [\fICIB\fR [...]] 
[--format \fIFORMAT\fR] [--select \fICOLUMN\fR] [--sort \fISORT\fR]
[--properties \fIPROPERTIES\fR] [--from \fIFROM\fR] [--to \fITO\fR]
.br
.\"
.SH DESCRIPTION
. \"
SAPHanaSR-replay-archive can be used to re-play SAPHanaSR status changes info
from a crm_report archive or pengine directory.
.br
Therefor it searches a given crm_report archive or pengine directory for pe-input
files and shows status information in historical order. Basically SAPHanaSR-showAttr
is called for each pe-input file.
.\"
.SH OPTIONS
.\"
.TP
\fB--help\fR
show help
.\" .TP
.\" \fB--version\fR
.\" show version
.TP
\fB--cib\fR \fICIB\fR [\fICIB\fR [...]]
specify the path to CIB file(s) (alteranative for --dir)
.TP
\fB--dir\fR \fIDIR\fR [\fIDIR\fR [...]] 
specify the directory where to search for cib files (alternative for --cib)
.TP
\fB--format\fR [ table | path | script | json ]
output format, default is table.
.TP
\fB--from\fR "\fIYYYY-MM-DD HH:MM:SS\fR"
from which point in time to show
.TP
\fB--sid\fR \fISID\fR
specify the SID to check for
.TP
\fB--sort\fR \fICOLUMN\fR
specify the column name to sort by
.TP
\fB--select\fR [ default | test | minimal | sr | all ]
selecton of attributes to be printed, default is default
.TP
\fB--to\fR "\fIYYYY-MM-DD HH:MM:SS\fR"
to which point in time to show
.TP
\fB--properties\fR \fIPROPERTIES\fR
specify the properties file
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.\"
* Replay SAPHanaSR-showAttr data from crm_report.
.PP
Report archive is crm_report-08-05-2024.tar.gz, extracted directory is
crm_report-08-05-2024, SID is EVA.
.PP
.RS 2
# tar xf crm_report-08-05-2024.tar.gz
.br
# SAPHanaSR-replay-archive --sid EVA --dir crm_report-08-05-2024/
.RE
.PP
* Replay SAPHanaSR-showAttr data from local node, use parseable output format.
.PP
Data is shown for times where the local node has been DC, SID is taken from current cib.xml.
.PP
.RS 2
# SAPHanaSR-replay-archive --dir /var/lib/pacemaker/ --format script
.RE
.\"
.SH FILES
.\"
.TP
/usr/bin/SAPHanaSR-replay-archive
the program itself.
.TP
/usr/bin/SAPHanaSR-showAttr
the working horse.
.TP
/var/lib/pacemaker/pengine/
usual local pengine log directory.
.TP
<CRM_REPORT_DIR>/<DC_NODE>/pengine/pe-input-<NUM>.bz2
extracted pe-input files.
.TP
<CRM_REPORT_DIR><DC_NODE>/cib.xml
extracted CIB file.
.\"
.SH REQUIREMENTS
.\"
* Python 3.6 runtime environment or compatible.
.\"
.SH BUGS
\"
Feedback is welcome, please mail to feedback@suse.com.
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-angi\fP(7), \fBSAPHanaSR-showAttr\fP(8) ,
\fBcrm_report\fP(8) , \fBcrm_simulate\fP(8) , \fBtar\fP(1)
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.\"
.SH COPYRIGHT
.\"
(c) 2019-2025 SUSE LLC
.br
SAPHanaSR-replay-archive comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
