.\" Version: 0.160.1
.\"
.TH SAPHanaSR-manageProvider 8 "19 Aug 2022" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-manageProvider \- adds, updates, removes or shows HADR provider sections for SAP HANA
.\"
.SH SYNOPSIS
\fBSAPHanaSR-manageProvider\fR [ --help | --version ]
.br
\fBSAPHanaSR-manageProvider\fR [ --sid=SID ] [--reconfigure] --add <template-file>
.br
\fBSAPHanaSR-manageProvider\fR [ --sid=SID ] [--reconfigure] --remove <template-file>
.br
\fBSAPHanaSR-manageProvider\fR [ --sid=SID ] [--reconfigure] --show --provider=<provider>
.\"
.SH DESCRIPTION
SAPHanaSR-manageProvider allows to add (and update), to remove and show SAP HANA
HADR provider sections. This is possible online and offline. It is possible on 
the primary as well as on the secondary.
.PP
.SH OPTIONS
.TP 4
\fB --help\fR
show help.
.TP 4
\fB --version\fR
show version.
.TP 4
\fB --add ...\fR
Add the section given in the template-file.
.TP 4
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.TP 4
# SAPHanaSR-manageProvider --show --provider=suschksrv
shows the global.ini section ha_dr_provider_suschksrv, if available
.TP 4
# SAPHanaSR-manageProvider --add ...
adds... 
.TP 4
# SAPHanaSR-manageProvider --remove ...
remove ...
.TP 4
# SAPHanaSR-manageProvider --show ...
show ...
.\"
.SH FILES
.TP
/usr/sbin/SAPHanaSR-manageProvider
the program itself.
.TP
setParameter.py
the SAP python script to interact with global.ini.
.\"
.SH BUGS
Command hangs, if it needs an input file and you do not specify the file.
.\"
.SH SEE ALSO
\fBocf_suse_SAPHanaController\fP(7) , \fBocf_suse_SAPHanaTopology\fP(7) ,
\fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR-replay-archive\fP(8) , \fBSAPHanaSR-filter\fP(8) ,
\fBSAPHanaSR-monitor\fP(8) , \fBSAPHanaSR_maintenance_examples\fP(7) ,
\fBSAPHanaSR-manageAttr\fP(8) ,
\fBcrm_simulate\fP(8) , \fBcrm_report\fP(8) , \fBcibadmin\fP(8) , \fBcrm_mon\fP(8) ,
\fBcs_convert_time\fP(8) , \fBcs_clusterstate\fP(8) , \fBcs_show_hana_info\fP(8) , \fBcs_show_scores\fP(8) ,
.br
https://documentation.suse.com/sbp/all/?context=sles-sap ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://www.susecon.com/doc/2015/sessions/TUT19921.pdf ,
.br
https://www.susecon.com/doc/2016/sessions/TUT90846.pdf ,
.br
https://www.susecon.com/archive-2020.html
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.\"
.SH COPYRIGHT
(c) 2022 SUSE LLC
.br
SAPHanaSR-manageProvider comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
