.\" Version: 1.2 
.\"
.TH SAPHanaSR-showAttr_properties 8 "06 Feb 2025" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-showAttr_properties \- SAPHanaSR-showAttr properties.
.\" TODO name
.\"
.PP
.SH DESCRIPTION
.\" TODO description
.\"
.SH SYNTAX
.\" TODO syntax
.PP
.\"
.SH EXAMPLES
.\" TODO examples
.PP
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-showAttr
the program itself.
.PP
.\"
.SH BUGS
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-showAttr\fP(8) , \fBSAPHanaSR-replay-archive\fP(8) ,
.PP
.\"
.SH AUTHORS
.PP
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2025 SUSE LLC
.br
SAPHanaSR-showAttr comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
