.\" Version: 1.2 
.\"
.TH SAPHanaSR-ScaleOut-XSA 7 "26 Nov 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
SAPHanaSR-ScaleOut-XSA \- Automating SAP HANA system replication for stand-alone XSA setups.
.PP
.\"
.SH DESCRIPTION
.\"
This manual page SAPHanaSR-ScaleOut-XSA provides information for setting up and
managing automation of SAP HANA system replication (SR) in scale-out setups with
a stand-alone eXecution Service Advanced (XSA) server. 
For other scale-out setups, please refer to SAPHanaSR-ScaleOut(7).
.PP
\fBThe SAP HANA SR scale-out stand-alone XSA setup is a technology preview.\fP
.PP
.\"
.\" .SH EXAMPLES
.\" .PP
.\"
.SH REQUIREMENTS
.\"
* NFS shared between sites for the XSA fss directory.
.\" TDODO fss
.PP
* fss configured identically in xscontroller.ini on both sites.
.PP
* Linux user <sid>adm same UID and GIDs on all cluster nodes.
.PP
* SAP HANA host auto-failover is not supported.
.PP
* See also REQUIREMENTS section in SAPHanaSR-ScaleOut(7).
.PP
\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
SAPHanaSR-angi(7) , SAPHanaSR-ScaleOut(7) , SAPHanaSR-angi-scenarios(7) .
.PP
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2025 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
