.\" Version: 1.2 
.\"
.TH SAPHanaSR-ScaleOut-XSA 7 "26 Nov 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
SAPHanaSR-ScaleOut-XSA \- Automating SAP HANA system replication for stand-alone XSA setups.
.PP
.\"
.SH DESCRIPTION
.\"
This manual page SAPHanaSR-ScaleOut-XSA provides information for setting up and
managing automation of SAP HANA system replication (SR) in scale-out setups with
a stand-alone eXtended application Services Advanced (XSA) server. 
For other scale-out setups, please refer to SAPHanaSR-ScaleOut(7).
.PP
\fBThe SAP HANA SR scale-out stand-alone XSA setup is a technology preview.\fP
.PP
.\"
.SH EXAMPLES
.PP
\fB*\fP Example Filesystem Storage entry.
.PP
TODO . SID is HA1.
.PP
/hana/shared/HA1/global/hdb/custom/config/xscontroller.ini
.PP
.RS 2
[fss]
.br
fss_storage_path = /hana/shared/HA1/xs/controller_data/ 
.RE
.PP
\fB*\fP Example /etc/fstab
.PP
Below is an fstab example for a shared filesystem holding XSA fss TODO. 
The filesystem is statically mounted on all nodes of the cluster. The correct
mount options are depending on the NFS server. However, client-side write
caching has to be disabled in any case. The path has to match fss_storage_path
in xscontroller.ini.
.PP
.RS 2
nfs1:/s/ha1/fss /hana/shared/HA1/xs/controller_data/ nfs4 rw,noac,sync,default 0 0
.RE
.PP
Note: The NFS share might be monitored, but not mounted/umounted by the HA cluster.
See ocf_suse_SAPHanaFilesystem(7) for details.
.RE
.PP
.\"
.SH FILES
.\"
.TP
/hana/shared/<SID>/global/hdb/custom/config/xscontroller.ini
TODO configuration.
.TP
/hana/shared/<SID>/xs/controller_data/fss/
default Filesystem Storage directory.
.TP
/etc/passwd , /etc/groups
local users and groups definition files.
.TP
/etc/fstab
TODO
.PP
.\"
.SH REQUIREMENTS
.\"
\fB*\fP The SAP HANA XSA service is installed for DNS wildcard based routing.
.PP
\fB*\fP NFS shared between sites for the XSA fss directory.
.\" TODO fss
.PP
\fB*\fP Filesystem Storage (fss) is configured identically on both sites.
.PP
\fB*\fP Linux user <sid>adm same UID and GIDs on all cluster nodes.
.PP
\fB*\fP SAP HANA host auto-failover is not supported.
.PP
\fB*\fP See also REQUIREMENTS section in SAPHanaSR-ScaleOut(7).
.PP
\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
SAPHanaSR-angi(7) , SAPHanaSR-ScaleOut(7) , SAPHanaSR-angi-scenarios(7) ,
SAPHanaFilesystem(7) ,
.br
https://help.sap.com/docs/SAP_HANA_PLATFORM/6b94445c94ae495c83a19646e7c3fd56/99306be18a1f493b990cf9d8d90cd922.html?version=2.0.07 ,
.br
2245631 - Hana is unavailable with message: ...
.br
3449644 - Not able to change the XSA default_domain with xscontroller.ini
.PP
.\"
.SH AUTHORS
.\"
A.Briel, F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2025 SUSE LLC
.br
The package SAPHanaSR-angi comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
