.\" Version: 0.160.1
.\"
.TH SAPHanaSR-showAttr 8 "11 Nov 2022" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-showAttr \- Shows Linux cluster attributes for SAP HANA system replication.
.\"
.SH SYNOPSIS
\fBSAPHanaSR-showAttr\fR [ --help | --version | --path2table ]
.br
\fBSAPHanaSR-showAttr\fR [ --sid=SID[:INO] ] [ --sort=FIELD ] [ --format=FORMAT ] [ --cib=OFFLINE_CIB_FILE ]
.\"
.SH DESCRIPTION
SAPHanaSR-showAttr shows Linux cluster attributes for SAP HANA system replication automation.
The overall system replication (SR) state is shown as well as the HANA state
on each node.
Because the HANA srHook methods srConnectionChanged() and preTakeover() are
used, the respective information shows up as well.
The information is fetched from the Linux cluster information base (CIB), not
from HANA directly.
.PP
The output shows four sections, containing all or some of the listed
fields:
.\" TODO check with existing script.
.TP
Global section
.br
HANA system identifier (\fBGlobal\fP)
.br
date and time of record (\fBcib-time\fP)
.br
maintenance status of Linux cluster (\fBmaintenance\fP)
.br
filter for resource agent logging (\fBfilter\fP)
.br
Linux cluster scale-out multi-target support (\fBmts\fP)
.br
HANA primary replication site (\fBprim\fP)
.br
HANA secondary replication site (\fBsec\fP)
.br
HANA replication channel state, indicated by srConnectionChanged (\fBsrHook\fP)
.br
HANA replication state of secondary site, indicated by systemReplicationStatus.py (\fBsync_state\fP)
.br
Linux cluster update status (\fBupd\fP)
.TP
Resource section
.br
name of Linux cluster resource (\fBResource\fP)
.br
maintenance status of Linux cluster resource (\fBmaintenance\fP)
.TP
Site section
HANA site name (\fBSite\fP)
.br
SAPHanaSR last primary timestamp (\fBlpt\fP)
.br
HANA landscape status (\fBlss\fP)
.br
HANA current master nameserver for that site (\fBmns\fP)
.br
HANA system replication role (\fBsrr\fP)
.TP
Hosts section
.br
Linux hostname (\fBHosts\fP)
.br
state of the Linux cluster resource (\fBclone_state\fP)
.br
state of Linux cluster node (\fBnode_state\fP)
.br
actual and configured roles for HANA on that node (\fBroles\fP)
.br
actual master score on that node (\fBscore\fP)
.br
generation of resource agent (\fBgra\fP)
.br
generation of srHook (\fBgsh\fP)
.br
HANA site where the host sits (\fBsite\fP)
.br
HANA system replication mode (\fBsrmode\fP)
.br
maintenance state of Linux cluster node (\fBstandby\fP)
.br
HANA system replication status (\fBsync_state\fP)
.br
Linux cluster node fence status (\fBterminate\fP)
.br
HANA version (\fBversion\fP)
.br
HANA virtual host name (\fBvhost\fP)
.br
HANA system replication takeover action, indicated by preTakeover() (\fBsra\fP)
.br
HANA system replication takeover action history, (\fBsrah\fP)
.PP
Some fields are generated dynamically from the CIB. That fields are missing,
if no corresponding attribute exists, e.g. the standby field.
An incomplete compilation on field details and purpose follows below.
.\" TODO formatting below. better no indents, but bold item header?
.\" TODO check details for Scale-Out
.PP
.B clone_state
- clone state of the Linux cluster resource

Value: [ PROMOTED | DEMOTED | UNDEFINED | WAITING4LPA | WAITING4PRIM | WAITING4NODES | WAITING4REG ]

.\" TODO: what kind of attribute?
This variable is set by the SAPHanaController or SAPHana resource agent.
.br
PROMOTED marks on scale-up the master state of an instance, which makes an HANA
SR primary. On scale-out it indicates the master nameserver of the primary site.
.br
DEMOTED makes on scale-up an HANA SR secondary.
On scale-out all running nodes except the primary master nameserver are marked
as DEMOTED. The DEMOTED state can be transient, on the way to promoting.
.br
WAITING4LPA indicates potential risk of a dual primary situation.
The cluster is waiting for DUPLICATE_PRIMARY_TIMEOUT seconds before registering
the former HANA primary as new secondary.
.br
WAITING4PRIM indicates the cluster is waiting for the HANA primary becoming ready
in order to register the HANA secondary.
.br
WAITING4NODES indicates on scale-out that not enough nodes are available to
bring up a functional site, according to the HANA landscape configuration.
.br
WAITING4REG indicates potential risk of a dual primary situation.
The cluster is waiting for the administrator to manually register the former
HANA primary as new secondary.
.br
See also AUTOMATED_REGISTER and DUPLICATE_PRIMARY_TIMEOUT in ocf_suse_SAPHana(7) and
ocf_suse_SAPHanaController(7).
.PP
.B gra
- generation of resource agent

Value: [ \fIgeneration\fR ]

The RA generation attribute identifies which generation of the RA is running.
It helps determing RA's capabilities and performing cluster-wide upgrades of
RA and srHook. The generation should be same for both on all nodes of the
Linux cluster after successful upgrade.
See also gsh below and SAPHanaSR-manageAttr(8).
.PP
.B gsh
- generation of srHook

Value: [ \fIgeneration\fR ]

The srHook generation attribute identifies which generation of the srHook is running.
It helps determing srHook's capabilities and performing cluster-wide upgrades of
RA and srHook. E.g. starting with generation 2.0 the RA supports scale-out
multi-target system replication, which needs replacement of the old SAPHanaSR.py
by new SAPHanaSrMultiTarget.py.
See also gra above and SAPHanaSR-manageAttr(8).
.PP
.B mts
- Linux cluster scale-out multi-target support

Value: [ true | false ]

The multi-target support attribute identifies whether the Linux cluster supports
HANA scale-out multi-target system replication. This needs consistently updated
RA and srHook to be active on all Linux cluster nodes, including the majority
maker.
See also gra, gsh and SAPHanaSR-manageAttr(8).
.PP
.B upd
- Linux cluster update status

Value: [ ok | nok ]

.\" TODO
The update status attribute identifies whether the whole cluster has successfully
passed an update procedure.
See also mts above and SAPHanaSR-manageAttr(8).
.PP
.B maintenance
- maintenance status of Linux cluster or cluster resource

Value: [ true | false ]

This is a Linux cluster node attribute. It is set by an admin.
The attribute is shown after it has been changed from the default.
The field might appear or disappear, depending on cluster maintenance tasks.
See also the standby attribute below.
.PP
.B filter
- SAPHanaController or SAPHana filter for logging

Value: [ \fIfilter\fR ]

The filter is defined by hana_<sid>_glob_filter .
See ocf_suse_SAPHana(7) and ocf_suse_SAPHanaController(7) for details.
.PP
.B Global
- HANA system identifier

Value: [ \fISID\fR ]

The SID is the same for the pair of HANA system replication databases in the
cluster.
.\" TODO as well as for the ones outside connected by system replication.
.PP
.B Hosts
- Linux hostname

Value: [ \fIHOSTNAME\fR ]

The hostname has to follow UNIX RFC 1178. Additional rules specific to SAP
apply. E.g. length of hostname is limited to 13 characters.
.\" TODO SAP note.
See also the fields remoteHost and vhost.
.PP
.B lpt
- last primary timestamp

Value: [ \fIUNIX_EPOCH\fR | 30 | 10 | 0 ]

The node attribute lpa_<sid>_lpt or cluster attribute hana_<sid>_site_lpt_<site> is set by the SAPHanaController or SAPHana resource agent.
When the RA detects a running HANA SR primary on the node, it records the Unix Epoch time.
See section DUPLICATE_PRIMARY_TIMEOUT of ocf_suse_SAPHana(7) and ocf_suse_SAPHanaController(7).
.br
Auxiliary values are set for an HANA SR secondary. 30 means the instance is
evictable for primary. 10 means: not yet ready.
.PP
.B lss
- landscape status

Value: [ 4 | 3 | 2 | 1 | 0 ]

The site attribute lss shows the return code of HANA's landscapeHostConfiguration.py. See field A of the roles section below and ocf_suse_SAPHanaController(7).
.PP
.B mns
- master nameserver

Value: [ \fIHANA_MASTERNAMESERVER\fR ]

The cluster attribute hana_<sid>_site_mns_<site> shows the current HANA master
nameserver for the given site.
.\" The attribute is set by the SAPHanaTopology resource agent.
It is empty for sites outside the Linux cluster.
.PP
.B srr
- system replication role

Value: [ "P"rimary | "S"econdary | "N"one ]

The site attribute srr shows the current HANA system replication role for the
given scale-out site.
.\" The attribute is set by the SAPHanaTopology resource agent.
It is empty for sites outside the Linux cluster.
For scale-up see roles sub-field B of the Hosts section.
.PP
.B node_state
- state of the Linux cluster node

Value: [ online | offline ]
.\" TODO UNCLEAN | pending ?
.PP
.B op_mode
- HANA SR operations mode

Value: [ logreplay | delta_datashipping | logreplay_readaccess ]

The node attribute hana_<sid>_op_mode is set by SAPHanaTopology, according to the running HANA. The attribute is used by the SAPHanaController or SAPHana resource agent for setting up system replication. delta_datashipping is not recommended in the context of Linux clusters.
.PP
.B remoteHost
- HANA SR remote host

Value: [ \fIHOSTNAME\fR ]
.\" TODO [ \fIHOSTNAME\fR | \fIHANA_VIRT_HOSTNAME\fR ] ?

The node attribute hana_<sid>_remoteHost is set by SAPHanaTopology, according
to the running HANA.
The attribute is used by the SAPHanaController or SAPHana resource agent for
setting up system replication.
See also the fields Hosts and vhost.
.PP
.B Resource
- name of Linux cluster resource

Value:  [ \fIRESOURCENAME\fR ]

Name of the multi-state resource controlled by SAPHanaController or SAPHana.
.PP
.B roles
- actual and configured roles for HANA on that node

The roles field in the Hosts section has six sub-fields for scale-up (A:B:C:D:E:F). It has four sub-fields for scale-out (C:D:E:F). 
The sub-fields C:D:E:F are primarily useful for HANA scale-out.
For scale-up that four fields C:D:E:F should be master1:master:worker:master.
.\" TODO or ":shtdown:shtdown:shtdown"
.br

Field A: return code of landscapeHostConfiguration.py
.br
Value: [ 4 | 3 | 2 | 1 | 0 ]
.br
This field contains the return code of landscapHostConfiguration.py. The
parameter does not tell you if the secondary system is ready for a takeover.
The meaning is different from common Linux return codes.
.br
4 = OK - Everything looks perfect on the HANA primary.
.br
3 = WARNING - A HANA Host Auto-Failover is taking place.
.br
2 = INFO - The landscape is completely functional, but the actual role of the host differs from the configured role.
.br
1 = DOWN - There are not enough active hosts.
.br
0 = FATAL - Internal script error, the state could not be determined.
.br
See landscapeHostConfiguration.py.
.br

Field B: HANA System Replication Role
.br
Value: [ "P"rimary | "S"econdary | "N"one ]
.br
See field srr of the Site section for scale-out.
.br

Field C: NameServer Config Role
.br
Value: [ master1 | master2 | master3 | worker | slave | standby | shtdown ]
.br

Field D: NameServer Actual Role
.br
Value: [ master | slave | standby | shtdown ]
.br

Field E: IndexServer Config Role
.br
Value: [ master1 | master2 | master3 | worker | slave | standby | shtdown ]
.br

Field F: IndexServer Actual Role
.br
Value: [ master | worker | slave | standby | shtdown ]
.br
.\" TODO details for scale-up
.\" scale-out: master1:master:worker:master | master1:slave:standby:standby | :shtdown:shtdown:shtdown | ... [ master1 | master2 | master3 | worker | slave | shtdown ]
.PP
.B score
- actual master score on that node

.\"scale-up:
.\"Value: [ 150 | 140 | 100 | 90 | 80 | 60 | 10 | 0 | -1 | -INFINITY ]
Value: [ 150 | 145 | 140 | 115 | 110 | 100 | 90 | 80 | 70 | 60 | 10 | 5 | 0 | -1 | -9000 | -10000 | -12200 | -22100 | -22200 | -32300 | -33333 | -INFINITY ]

This is a variable of the SAPHanaController or SAPHana resource agent. It is calculated
based on an internal scoring table. A value of 150 should cause the Linux cluster promoting
the local resource instance to HANA SR primary master nameserver.
140 indicates a HANA primary master nameserver candidate. 
100 indicates the HANA secondary master nameserver. This field should not be empty.

Note: The effective resource scoring used by the Linux cluster differs from the above
values because the cluster engine takes into account other factors as well.  
.PP
.B site
- HANA site where the host sits

Value: [ \fIHANA_SITE\fR ]

The node attribute hana_<sid>_site is set by SAPHanaTopology, according to the running HANA.
The attribute is used by the SAPHanaController or SAPHana resource agent for setting up
system replication.
A dash (-) indicates the RA did not run or did not recognize the site.
.PP
.B srmode
- HANA SR mode

Value: [ sync | syncmem ]

The node attribute hana_<sid>_srmode or cluster attribute hana_<sid>_glob_srmode is set by SAPHanaTopology, according to the running HANA.
The attribute is used by the SAPHanaController or SAPHana resource agent for setting up system
replication. SAP HANA knows also async and fullsync (see URLs below).
Those do not make sense for automating HANA system replication by an Linux cluster.
.PP
.B standby
- maintenance state of Linux cluster node

Value: [ on | off ]

This is a Linux cluster node attribute. It is set by an admin.
The attribute is shown after it has been changed from the default.
The field might appear or disappear, depending on cluster maintenance tasks.
See also the maintenance attribute above.
.PP
.B sync_state
- HANA SR status

Value: [ SOK | SFAIL | SWAIT | SREG | PRIM ]

.\"TODO cluster property sync_state ?
The cluster property hana_<sid>_glob_sync_state is set by the SAPHanaController or SAPHana resource agent.
The first three values are representing an HANA system replication status,
recognized at latest RA run, see ocf_suse_SAPHana(7), ocf_suse_SAPHanaController(7) and
systemReplicationStatus.py .
.br
The 4th value (PRIM) just indicates an HANA SR primary.
.PP
.B sra
- HANA system replication action

Value: [ T | R | - ]

The node attribute system replication action is checked by the HA/DR provider susTkOver.py using the API
method preTakeover(). It is set by the resource agent SAPHana or SAPHanaController. 
It indicates whether a takeover or registration is ongoing. This attribute may 
not be persisted in pengine files.
.br
T = Takeover on new primary (sr_takeover) ongoing.
.br
R = Registration on new secondary (sr_register) ongoing.
.br
- = No action pending.
.PP
.B srah
- HANA system replication action history

Value: [ T | R | - ]

The node attribute system replication action history stores actions in CIB
attributes for later use, for root cause analysis.
.PP
.\" TODO check srHook
.B srHook
- HANA replication channel state, indicated by srConnectionChanged

Value: [ SOK | SFAIL | SWAIT | SREG | PRIM ]

The cluster attributes related to srHook are hana_<sid>_site_srHook_<site> for the multi-tier enabled hook and hana_<sid>_glob_srHook for the old-style hook.
It represents the HANA SR status from HA/DR provider API method srConnectionChanged(). See SAPHanaSR-ScaleOut(7) for supported API versions and scenarios.
The attribute is not updated if the cluster is not running. Thus if the cluster is shut down while HANA remains running, the content of srHook might be outdated on cluster start until the next srConnectionChanged() event.
See SAPHanaSR.py(7) and SAPHanaSrMultiTarget.py(7) for details. 
.br
The cluster property \fBhana_<sid>_glob_srHook\fR shows one HANA SR status.
It does not work for multi-tier and multi-target system replication.
\fBhana_<sid>_site_srHook_<site>\fR shows the HANA SR status specific to the
respective site.
.br
Note: Global and site-specific properties must not appear at same time.
.PP
.B terminate
- Linux cluster node fence status

Value: [ true ]

Indicates whether that node is requested for being fenced from outside the
Linux cluster. The attribute is removed as soon as the node has been successfully
fenced.
.PP
.B version
- HANA version

Value: [ \fIHANA_VERSION\fR ]

.\"TODO set by ...
Version of the HANA instance on that node. Of course, should be supported for
the given Linux version.
Should be same on all nodes, except during specific HANA upgrade procedure.
.PP
.B vhost
- HANA virtual hostname

Value: [ \fIHANA_VIRT_HOSTNAME\fR ]

The virtual hostname is used by the HANA instance instead of Linux hostname.
The node attribute hana_<sid>_vhost is set by SAPHanaTopology, according to
the running HANA. The attribute is used by the SAPHanaController or SAPHana
resource agent for setting up system replication.
See also the fields Hosts and remoteHost. SAPHanaToplogy needs the SAPHOSTAGENT
to map from the local hostname to the HANA virtual hostname.
.\" TODO details, see HANA global.ini
.\"
.SH OPTIONS
.TP 4
\fB --help\fR
show help.
.TP 4
\fB --version\fR
show version.
.TP 4
\fB --path2table\fR
convert script-style input pipe back into normal output.
.TP 4
\fB --sid=\fISID\fR[:\fIINO\fR]
use SAP system ID \fISID\fR. Should be autodetected, if there is only one SAP HANA instance installed on the local cluster node. The SAP system ID is a 3 alphanum string with a valid SAP system name like SLE, HAE, FH1, C11, or P42.
Optional: Use SAP instance number \fIINO\fR. Should be autodetected, if there is only one SAP HANA instance installed on the local cluster node. The SAP instance number must be represented by a two digit numer like 00, 05 or 42. Some numbers ares not allowed, e.g. 98.
.TP 4
\fB --sort \fIFIELD\fR
sort Hosts section table by field. Allowed values: roles, site. The default sort is by hostnames.
.\" TODO --format
.\" .TP 4
.\" \fB --format \fIFORMAT\fR
.\" output format. Allowed values: [ text | HTML ]. Default is text.
.TP 4
\fB --cib=\fIOFFLINE_CIB_FILE\fR
read data from given offline CIB file.
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.TP 4
# SAPHanaSR-showAttr
show all SAPHanaSR attributes and relevant cluster maintenance states.
.br
If the roles sub-fields are 1:P:::: landscapeHostConfiguration.py has not been able to detect the HANA roles during last recent RA monitor operation. Likely HANA was down or sudo <sid>adm failed.
.TP 4
# SAPHanaSR-showAttr --sort roles
show all SAPHanaSR attributes in the cluster and sort host table output by roles.
.TP 4
# SAPHanaSR-showAttr --sid=HA1:10 --cib=./hb_report-17-07-2019/grauenstein01/cib.xml
show all SAPHanaSR attributes for SAP System ID HA1 and instance number 10 from given CIB file.
.TP 4
# SAPHanaSR-showAttr | grep -e master: -e worker: -e slave:
show SAPHanaSR promotion scores on running nodes.
.TP 4 
# SAPHanaSR-showAttr --format=script | egrep -v '/(version|op_mode|vhost|remoteHost|node_state|site)=' | SAPHanaSR-showAttr --path2table
reduce output to selected fields.
.\"
.SH FILES
.TP
/usr/sbin/SAPHanaSR-showAttr
the program itself.
.TP
/usr/lib/SAPHanaSR-ScaleOut/SAPHanaSRTools.pm
needed functions.
.TP
/usr/sap/hostctrl/exe/saphostctrl
the SAP host control command.
.\"
.SH BUGS
Formatting and content of this script's output will change, since this script
is under development. This script is not intended to be called from monitoring
tools.
For monitoring please use SAPHanaSR-monitor instead.
.br
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.\"
.SH SEE ALSO
\fBocf_suse_SAPHanaController\fP(7) , \fBocf_suse_SAPHanaTopology\fP(7) ,
\fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR-replay-archive\fP(8) , \fBSAPHanaSR-filter\fP(8) ,
\fBSAPHanaSR-monitor\fP(8) , \fBSAPHanaSR_maintenance_examples\fP(7) ,
\fBSAPHanaSR-manageAttr\fP(8) ,
\fBcrm_simulate\fP(8) , \fBcrm_report\fP(8) , \fBcibadmin\fP(8) , \fBcrm_mon\fP(8) , \fBcrm_attribute\fP(8) ,
\fBcs_convert_time\fP(8) , \fBcs_clusterstate\fP(8) , \fBcs_show_hana_info\fP(8) , \fBcs_show_scores\fP(8) ,
.br
https://documentation.suse.com/sbp/all/?context=sles-sap ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://www.susecon.com/doc/2015/sessions/TUT19921.pdf ,
.br
https://www.susecon.com/doc/2016/sessions/TUT90846.pdf ,
.br
https://www.susecon.com/archive-2020.html
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.\"
.SH COPYRIGHT
(c) 2014 SUSE Linux Products GmbH, Germany.
.br
(c) 2015-2017 SUSE Linux GmbH, Germany.
.br
(c) 2018-2022 SUSE LLC
.br
SAPHanaSR-showAttr comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
