= SAPHanaSR-showAttr-adoc(1)
Lars Pinne, Fabian Herschel
v1.001
:doctype: manpage
:manmanual: SAPHanaSR-showAttr-adoc
:mansource: SAPHanaSR-showAttr-adoc
:man-linkstyle: pass:[blue R < >]

== Name

SAPHanaSR-showAttr - Shows Linux cluster attributes for SAP HANA system replication.

== Synopsis

SAPHanaSR-showAttr [ --help | --version | --path2table ]

SAPHanaSR-showAttr\fR [ --sid=SID[:INO] ] [ --select=SELECTION ] [ --sort=FIELD ] [ --format=FORMAT ] [ --cib=OFFLINE_CIB_FILE ] 

== 

SAPHanaSR-showAttr shows Linux cluster attributes for SAP HANA system replication automation.
The overall system replication (SR) state is shown as well as the HANA state
on each node.
Because the HANA srHook methods srConnectionChanged() and preTakeover() are
used, respective information shows up as well.
The information is fetched from the Linux cluster information base (CIB), not
from HANA directly.
Fields to be shown can be specified by pre-defined selections via command line option.

The output shows four sections, containing all or some of the listed
fields:

Global section

*global (Global)*:: 
  constant

*cib-time*::
  date and time of record

== Exit status

TODO

*0*::
  TODO 0 

*1*::
  TODO 1

== Resources

== Copying

Copyright (C) 2014 {author}. +
