#!/usr/bin/bash

function run() {
    local node="$1" testID="$2" repeat="$3" sleep="$4"
    logFile="testLog$(date +"%Y-%m-%d").txt"
    logLink="testLog.curr.txt"
    if [ ! -f "$logFile" ]; then
        touch "$logFile"
    fi
    if [ -L "$logLink" ]; then
        rl=$(readlink "$logLink")
        if [[ "$rl" != "$logFile" ]]; then
            ln -s -f "$logFile" "$logLink"
        fi
    else
        ln -s "$logFile" "$logLink"
    fi
    saphanasrlib.py --testFile="$test_dir/${testID}.json" \
                            --remoteNode="$node" \
                            --repeat="$repeat" \
                            --dumpFailures \
                            --defaultChecksFile="$test_dir/defaultChecks.json" \
                            --properties="$test_dir/properties.json" \
                            --logFile "$local_dir/$logFile"
    # ln -s -f testLog2023-03-31.txt testLog.curr.txt
    sleep "$sleep"; 
    return 0
}

test_scenario="angi-ScaleUp"
local_dir="$PWD"
test_dir="/usr/local/share/tester/json/$test_scenario"

while true; do  
    run ifen02 kill_prim_inst  3 600
    run ifen02 free_log_area 1 60
    run ifen02 kill_prim_inst  1 120
    run ifen02 free_log_area 1 60
    run ifen02 restart_cluster_turn_hana  1 300
    run ifen02 ssn  2 300
    run ifen02 kill_secn_inst  3 300
    run ifen02 spn  2 300
    run ifen02 sap  1 300
    run ifen02 kpx  1 300
    run ifen02 nop  1  10 
    run ifen02 ksx  1 300
    run ifen02 maintenance_cluster_turn_hana 1 300
    run ifen02 restart_cluster  1 300
    run ifen02 restart_cluster_hana_running   1 300
    run ifen02 bmt  1  60
done 
