#!/usr/bin/bash

function run() {
    local testID="$1" test_prop="$2" repeat="$3" sleep="$4"
    logFile="testLog$(date +"%Y-%m-%d").txt"
    logLink="testLog.curr.txt"
    if [ ! -f "$logFile" ]; then
        touch "$logFile"
    fi
    if [ -L "$logLink" ]; then
        rl=$(readlink "$logLink")
        if [[ "$rl" != "$logFile" ]]; then
            ln -s -f "$logFile" "$logLink"
        fi
    else
        ln -s "$logFile" "$logLink"
    fi
    SAPHanaSR-testCluster --testFile="$test_dir/${testID}.json" \
                            --repeat="$repeat" \
                            --dumpFailures \
                            --defaultsFile="$test_dir/defaults.json" \
                            --properties="$test_prop" \
                            --remoteNodes $nodes \
                            --logFile "$local_dir/$logFile"
    # ln -s -f testLog2023-03-31.txt testLog.curr.txt
    sleep "$sleep"; 
    return 0
}

test_scenario="angi-ScaleUp"
test_case="nop"
test_prop="properties"
local_dir="$PWD"
nodes=""

while [ $# -gt 0 ]; do
    case "$1" in
        --test_scenario=* )
                test_scenario=${1#*=}
                ;;
        --node=* )
                nodes="$nodes ${1#*=}"
                ;;
        --properties=* )
                test_prop=${1#*=}
                ;;
    esac
    shift
done

test_dir="/usr/share/SAPHanaSR-tester/json/$test_scenario"

# TODO: test sequence should come from a json test sequence file
echo "nodes: $nodes, test_scenario=$test_scenario"
while true; do  
    run flup "$test_prop" 1 60
done 
