#!/bin/bash

# Helper script for the TakeOver Hook to detect mainteance mode of whole
# cluster or of clone or multi-state ressource
# return 0, if no maintenance
# return 5, if any maintenance
# do not use '1' as return value, so we can distinguish between the return of
# the helper script and an error of 'sudo'

# For now we only check the multi-state ressource (as descibed in the official supported maintenance procedure described in man page SAPHanaSR_maitenance_examples(7) - EXAMPLES: * Perform an SAP HANA take-over by using SAP tools. 

HSID=$1
mmaint="false"

cibtmp=$(mktemp /tmp/SAPHanaSR_SRHhelper.XXXXXX)
cibadmin -Q > "$cibtmp"

# get primitives
prims="$(xmllint -xpath "//*/primitive[@class='ocf' and @provider='suse']/@id" "$cibtmp" | sed -e 's/id=//g' -e 's/"//g')"
for ps in $prims; do
    sid=$(xmllint -xpath "string(//primitive[@id='$ps']/instance_attributes/nvpair[@name='SID']/@value)" "$cibtmp")
    if [ "$sid" != "$HSID" ]; then
        # SID does not match, skipping
        continue
    fi
    rname=$(xmllint -xpath "string(//*[primitive[@id='$ps']]/@id)" "$cibtmp")
    rtype=$(xmllint -xpath "name(//*[@id='$rname'])" "$cibtmp")

    # multi-state resource - master/Promoted
    if [ "$rtype" == "master" ] || [ "$rtype" == "Promoted" ]; then
         # found multi-state resource name
         if crm_mon -r1 | grep "$rname" | grep unmanaged >/dev/null 2>&1; then
             mmaint="true"
         fi
    fi
done
rm -f "$cibtmp"
if [ "$mmaint" == "true" ]; then
    exit 5
fi
exit 0
