#!/bin/bash
#
# test_freeze_prim_fs - freeze fs in primary side
src=${BASH_SOURCE[0]}
full_path=$(readlink -f  "$src")
dir_path=$(dirname "$full_path")
source .test_properties
currPrimary="$(ssh "${node01}" "/usr/bin/SAPHanaSR-showAttr --format=tester" | awk -F'/' '/score="150"/ { print $2 }' )"

echo "==== Un-Freeze SAP HANA FS ===="

ports="4${instNr}01,4${instNr}02,4${instNr}03"

ssh "$currPrimary" 'fsfreeze --unfreeze /hana/shared/'"${SID}"
sleep 60
