#!/bin/bash
#
# sct_test_unfreeze_prim_master_nfs - unfreeze nfs on primary master
src=${BASH_SOURCE[0]}
full_path=$(readlink -f  "$src")
dir_path=$(dirname "$full_path")
source .test_properties
currPrimary="$(ssh "${node01}" "/usr/bin/SAPHanaSR-showAttr --format=tester" | awk -F'/' '/score="150"/ { print $2 }' )"
currPrimWorker="$(ssh "${node01}" "/usr/bin/SAPHanaSR-showAttr --format=tester" | awk -F'/' '/score="-10000"/ { print $2 }' )"

echo "==== Un-Freeze SAP HANA NFS ===="

ssh "$currPrimary" 'iptables -D OUTPUT -p tcp -m multiport --ports 2049 -j DROP'
sleep 60
#
