#!/bin/bash
#
# sct_test_delete_cluster_config  - delete the complete cluster config (CIB)
#
# - set cluster to maintenance
# - erase the cluster config
#
# expected outcome: cluster config (CIB) empty, HANA still running 
src=${BASH_SOURCE[0]}
full_path=$(readlink -f  "$src")
dir_path=$(dirname "$full_path")
source .test_properties


#
# set cluster to maintenance, erase the cluster configuration (CIB) and again set cluster to maintenance 
#
ssh "${node01}" "crm maintenance on"
ssh "${node01}" "crm configure erase"
ssh "${node01}" "crm maintenance on"

#
# restart the cluster - this deletes transient attributes from the cluster
#
ssh "${node01}" "crm cluster stop --all"
ssh "${node01}" "cs_wait_for_idle -s 5"
ssh "${node01}" "crm cluster start --all"
ssh "${node01}" "cs_wait_for_idle -s 5"

#
# delete persistent node attributes
#
ssh "${node01}" <<EOF
crm configure show type:node | awk -F'\' '/^node / { print \$1 } ' >/root/crm.txt
crm configure load update /root/crm.txt
rm /root/crm.txt
EOF

ssh "${node01}" "cs_wait_for_idle -s 5"

#
# take cluster out of maintenance
#
ssh "${node01}" "crm maintenance off"
ssh "${node01}" "cs_wait_for_idle -s 5"
#
