#!/bin/bash
#
# test_block_sap_hana_sr - block ports for SAP HANA SR in multi-db installation (4xx01 - 4xx03)
# iptables -D INPUT -p tcp -m multiport --ports 40001,40002,40003 -j DROP
# iptables -I INPUT -p tcp -m multiport --ports 40001,40002,40003 -j DROP
# about sap hana ports: https://www.stechies.com/hana-services-ports-interview-questions-answer/
src=${BASH_SOURCE[0]}
full_path=$(readlink -f  "$src")
dir_path=$(dirname "$full_path")
source "$dir_path/test_properties"
source .test_properties
currPrimary="$(ssh "${node01}" "SAPHanaSR-showAttr --format=tester" | awk -F'/' '/score="150"/ { print $2 }' )"

echo "==== Un-Block SAP HANA SR ===="

ports="4${instNr}01,4${instNr}02,4${instNr}03"

ssh "$currPrimary" 'iptables -D INPUT -p tcp -m multiport --ports '"$ports"' -j DROP'
ssh "$currPrimary" 'iptables -D OUTPUT -p tcp -m multiport --ports '"$ports"' -j DROP'
sleep 60
