#!/bin/bash
#
# test_kpi (ScaleUp)
# 2023-02-24
# test steps expected see kpi.json
#
########
#
# usage:
# test_XX --node=<clusterNode> --testCase=<testCase> --testFile=<testFile> [--verbose]

set -u
source ./test-lib

#
# globals testCase(r)
#
function main() {
    local rc1 rc2
    local rc=3
    local startStep currStep
    startStep="$(search4getValue "Tests/$testCase/start")"
    echo "testCase=$testCase, startStep=$startStep"
    checkPrerequisites "${testCase}-$startStep"; rc1="$?"
    if [[ "$rc1" != 0 ]]; then
       message "RESULT: PREREQUISITES NOT MATCHED"
       rc=2
    else
        currStep="$(search4getValue "Steps/${testCase}-${startStep}/next")"
        checkSequence "$testCase" "$currStep"; rc2="$?"
        if [[ "$rc2" == 0 ]]; then
            message "RESULT: TEST SUCCESS"
            rc=0
        else
            message "RESULT: TEST FAILED" 
            rc=1
        fi
    fi
    return "$rc"
}

# --node=<clusterNode> --testCase=<testCase> --testFile=<testFile>
init "$@"
main
