#!/bin/bash
node01="basf01"
node02="basf02"
mstResource="ms_SAPHanaCon_HA1_HDB00"
sidadm="ha1adm"

# shellcheck disable=SC2029
ssh "$node01" "crm resource cleanup  $mstResource"

ssh "$node02" 'crm cluster run "crm cluster stop"'

echo "==== SUSE Cluster Stopped ===="

 ssh "$node01" 'su - '"$sidadm"' -c "HDB start"' &
 ssh "$node02" 'su - '"$sidadm"' -c "HDB start"' &

wait

echo "==== SAP HANA DBs started ===="

ssh "$node01" 'crm cluster run "crm cluster start"'

echo "==== SUSE Cluster Started ===="

