#!/bin/bash
#
#
node01="basf01"
node02="basf02"
mstResource="ms_SAPHanaCon_HA1_HDB00"
srMode="sync"
opMode="logreplay"
instNr="00"

ssh ${node01} "crm resource cleanup  $mstResource"

currPrimary="$(ssh ${node01} "SAPHanaSR-showAttr --format=script" | awk -F'/' '/score="150"/ { print $2 }' )"
currSecondary="$(ssh ${node01} "SAPHanaSR-showAttr --format=script" | awk -F'/' '/score="100"/ { print $2 }' )"

echo "p=$currPrimary, s=$currSecondary"

sitePrimary=$(ssh ${node01} "SAPHanaSR-showAttr --format=script" | awk -F'=' '$0 ~ node".site" { print $2 }' node="$currPrimary")
sitePrimary="${sitePrimary//\"/}"

echo "p=$currPrimary ($sitePrimary), s=$currSecondary"


echo "==== SUSE Resource Maintenance Begin ===="
ssh ${node02} "crm resource maintenance $mstResource on"

set -x
ssh "$currSecondary" 'su - ha1adm -c "hdbnsutil -sr_takeover --suspendPrimary"'
ssh "$currPrimary" "su - ha1adm -c \"hdbnsutil -sr_register --remoteHost=$currSecondary --remoteInstance=$instNr --name=$sitePrimary --replicationMode=$srMode --operationMode=$opMode --online\""

sleep 30
ssh ${node02} 'cs_wait_for_idle -s 2'
ssh ${node02} "crm resource refresh $mstResource"

ssh ${node02} "crm resource maintenance $mstResource off"

echo "==== SUSE Resource Maintenance End ===="
