#!/bin/bash
#
# test_restart_cluster_hana_running - restart cluster with SAP HANA resource in maintenance
#
# - cleanup mst-resource
# - set cluster in maintenance mode
# - stop cluster
# - wait some time to simulate a maintenance
# - start cluster
# - wait till cluster is idle
# - refresh cln-resource 
# - wait till cluster is idle
# - refresh mst-resource 
# - wait till cluster is idle
# - end cluster maintenace mode
#
# expected outcome: cluster running, SAP HANA instances running, SR roles NOT exchanged
source test_properties

# shellcheck disable=SC2029
ssh "$node01" "crm resource cleanup  $mstResource"
ssh "$node01" "crm maintenance on"

ssh "$node02" 'crm cluster run "crm cluster stop"'

echo "==== SUSE Cluster Stopped ===="

sleep 60

ssh "$node01" 'crm cluster run "crm cluster start"'

sleep 120
ssh "$node01" "cs_wait_for_idle --sleep 60"


ssh "$node01" "crm resource refresh  $clnResource"
ssh "$node01" "cs_wait_for_idle --sleep 10"
ssh "$node01" "crm resource refresh  $mstResource"


ssh "$node01" "cs_wait_for_idle --sleep 10"
ssh "$node01" "crm maintenance off"

echo "==== SUSE Cluster Started ===="

