#!/bin/bash
# runtests
#
# (c) 2024-2026 SUSE LLC
# Author: F.Herschel, L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2026-01-02
#

CASFILE=/usr/share/SAPHanaSR-tester/samples/runtests_angi-ScaleOut_conservative.txt
source $CASFILE || exit 1

#PROPERTIES="./properties_angi-ScaleOut.json"
#ASTROOT=/usr/share/SAPHanaSR-tester/json/angi-ScaleOut
#LOGFILE="runtests.log"
REMOTENODES="peak11 peak21"

exec 3>&1
exec 1>>"$LOGFILE"

# TCASES="flup free_log_area $SECNCAS free_log_area $PRIMCAS free_log_area $BOTHCAS free_log_area"
TCASES="flup standby_prim_node free_log_area"

for TEST in $TCASES; do
  echo "#### $(date +%Y-%m-%d" "%H:%M:%S) run test: $TEST ####"
  for N in $REMOTENODES; do
    hana_fs="/hana"
    hana_fill=$(ssh $N "df --output=pcent $hana_fs | grep -v Use")
    echo "$(date +%Y-%m-%d\ %H:%M:%S) fill grade: $N $hana_fs $hana_fill"
  done
  SAPHanaSR-testCluster \
    --testFile "$ASTROOT/$TEST.json"
    --properties "$PROPERTIES" \
    --remoteNodes $REMOTENODES \
    --defaultsFile "$ASTROOT/defaults.json" \
    --logFile "$TEST.log" \
    --jsonOut "$TEST.json.out" \
    --dumpFailures >&3; rc=$?
  echo "#### $(date +%Y-%m-%d" "%H:%M:%S) end test: $TEST rc: $rc ####"
  if [[ "$rc" != "0" ]]; then
    exit 1
  else
    sleep 120
  fi
done
exit 0
#
