#!/bin/bash
#
##########################################################################
#
# SAPHanaSR-replay
#
# Author:       Fabian Herschel, November 2015
# Support:      linux@sap.com
# License:      GNU General Public License (GPL)
# Copyright:    (c) 2015      SUSE Linux GmbH
#
##########################################################################
#
# Syntax: 
# SAPHanaSR-replay <sid> <path-to-pengine-archive>
#
# SAPHanaSR-replay HA1   ~/customerXX/pcmk-Wed-18-Nov-2015/node01/pengine
#
##########################################################################
#
sid=$(echo "$1" | tr '[:upper:]' '[:lower:]')
cibDir="$2"
mkdir -p $cibDir/tmp
ls -tr $cibDir
for cibBZ2 in $cibDir/*.bz2; do 
   cib=${cibBZ2%.bz2}; 
   shortCIB=${cib##*/}
   echo "cib: $cib"; 
   bzip2 -c $cibBZ2 > $cibDir/tmp/$shortCIB; 
   #SAPHanaSR-monitor  --cib=$cibDir/tmp/$shortCIB --sid=cp1; 
   SAPHanaSR-showAttr --cib=$cibDir/tmp/$shortCIB --sid=$sid; 
   rm $cibDir/tmp/$shortCIB ;    
done 
