#!/usr/bin/perl
#
# get_all_lnx_attributes
#
# <nvpair id="status-lv9041-hana_lnx_roles" name="hana_lnx_roles" value="primary:master1:slave:worker:slave"/>

my $sid="lnx";


open CIB, "cibadmin -Ql |";

while (<CIB>) {
   chomp;
   if ( $_ =~ /nvpair\s+id="status-([a-zA-Z0-9]+)-\w+"\s+name="(\w+_${sid}_\w+)"\s+value="([^"]+)"/ ) {
       printf "%-8s %-20s %-30s\n", $1, $2, $3;
   }
}
