#!/bin/bash

   sid="lnx"
   node1="lv9041"
   node2="lv9042"


   node1_lpt=$(crm_attribute -N $node1 -G -n  lpa_${sid}_lpt -l reboot -q)
   node2_lpt=$(crm_attribute -N $node2 -G -n  lpa_${sid}_lpt -l reboot -q)


   node1_sync=$(crm_attribute -N $node1 -G -n  hana_${sid}_sync_state -l reboot -q)
   node2_sync=$(crm_attribute -N $node2 -G -n  hana_${sid}_sync_state -l reboot -q)

   node1_state=$(crm_attribute -N $node1 -G -n  hana_${sid}_clone_state -l reboot -q)
   node2_state=$(crm_attribute -N $node2 -G -n  hana_${sid}_clone_state -l reboot -q)


   if [ $node1_lpt -gt 3600 ]; then
	   node1_time=$(date -d @$node1_lpt)
   else
           node1_time="(secondary)"
   fi

   if [ $node2_lpt -gt 3600 ]; then
	   node2_time=$(date -d @$node2_lpt)
   else
           node2_time="(secondary)"
   fi

   echo "Last Primary Arbitration (LPA) Algorithm"
   echo "$(date)"
   echo "$node1: $node1_lpt : $node1_time (sync=$node1_sync, state=$node1_state)"
   echo "$node2: $node2_lpt : $node2_time (sync=$node2_sync, state=$node2_state)"

   if [ $node1_lpt -gt $node2_lpt ]; then
      echo "$node1 wins LPA"
   fi
   if [ $node2_lpt -gt $node1_lpt ]; then
      echo "$node2 wins LPA"
   fi
   if [ $node2_lpt -eq $node1_lpt ]; then
      echo "$node1 / $node2 LPA stalemate"
   fi
   
   
   ptest -sL | grep promo 
