#!/bin/bash
set -u

   sid="lnx"
   node1="lv9041"
   node2="lv9042"

format="%-10s %10s %-23s %-6s %-8s %-6s %-6s\n"

while [ $# -gt 0 ]; do
    case $1 in 
        -1 )
            ;;
        
    esac
    shift
done

function print_header()
{
   local node=$1 node_lpt=$2 node_sync=$3 node_state=$4 age=$5 promo=$6
   local node_time

   node_time="lpt"
   printf "$format" "$node" "$node_lpt" "$node_time" "$node_sync" "$node_state" "$age" "$promo"
}


function print_node()
{
   local node=$1 node_lpt=${2:--1} node_sync=$3 node_state=$4 age=$5 promo=$6
   local node_time

   if [ $node_lpt -gt 3600 ]; then
      node_time=$(date --d @$node_lpt +'%Y-%m-%d %T %Z')
   else
      node_time="--"
   fi
   printf "$format" "$node" "$node_lpt" "$node_time" "$node_sync" "$node_state" "$age" "$promo"
}

   node1_lpt=$(crm_attribute -N $node1 -G -n  lpa_${sid}_lpt -l reboot -q 2>/dev/null)
   node2_lpt=$(crm_attribute -N $node2 -G -n  lpa_${sid}_lpt -l reboot -q 2>/dev/null)


   node1_sync=$(crm_attribute -N $node1 -G -n  hana_${sid}_sync_state -l reboot -q 2>/dev/null)
   node2_sync=$(crm_attribute -N $node2 -G -n  hana_${sid}_sync_state -l reboot -q 2>/dev/null)

   node1_state=$(crm_attribute -N $node1 -G -n  hana_${sid}_clone_state -l reboot -q 2>/dev/null)
   node2_state=$(crm_attribute -N $node2 -G -n  hana_${sid}_clone_state -l reboot -q 2>/dev/null)

   node1_promo=$(ptest -sL 2>/dev/null | awk '$0 ~ "promotion score on "  h {print $6}' h=$node1 2>/dev/null)
   node2_promo=$(ptest -sL 2>/dev/null | awk '$0 ~ "promotion score on "  h {print $6}' h=$node2 2>/dev/null)

   s_state=$(crmadmin -q -S $(crmadmin -Dq 2>&1 1>/dev/null ) 2>&1 1>/dev/null)


   currtime=$(date +'%s')
   node1_lpt=${node1_lpt:--1}
   node2_lpt=${node2_lpt:--1}
   if [ $node1_lpt -gt 3600 ]; then
	   node1_time=$(date -d @$node1_lpt)
       (( node1_age = currtime - node1_lpt ))
   else
           node1_time=""
           node1_age="-"
   fi

   if [ $node2_lpt -gt 3600 ]; then
	   node2_time=$(date -d @$node2_lpt)
       (( node2_age = currtime - node2_lpt ))
   else
           node2_time=""
           node2_age="-"
   fi

   echo "Last Primary Arbitration (LPA) Algorithm"
   echo "Time: $(date -d @$currtime +'%Y-%m-%d %T %Z') Cluster-Status: $s_state"
print_header "Node" "lpt" "sync" "rcstat" "age" "promo"
print_node "$node1" "$node1_lpt" "$node1_sync" "$node1_state" "$node1_age" "$node1_promo"
print_node "$node2" "$node2_lpt" "$node2_sync" "$node2_state" "$node2_age" "$node2_promo"
echo

   if [ $node1_lpt -gt $node2_lpt ]; then
      echo "==> $node1 wins LPA"
   fi
   if [ $node2_lpt -gt $node1_lpt ]; then
      echo "==> $node2 wins LPA"
   fi
   if [ $node2_lpt -eq $node1_lpt ]; then
      echo "==> $node1 / $node2 LPA stalemate"
   fi
   
   
   # ptest -sL | grep promo 
