#!/usr/bin/perl
#
# get_all_lnx_attributes
# (c) 2014 SUSE Linux Products GmbH, Nuremberg Germany 
# (c) 2015 SUSE Linux GmbH, Nuremberg Germany 
# Author: Fabian Herschel
# License: GPL v2 
# Version: 0.6.2015.05.07.1
#
##################################################################

use POSIX;
use strict;
use Getopt::Long;

use lib '/usr/share/SAPHanaSR/tests';
use SAPHanaSRTools;

my $SID;
my $sid="";
my $table_title = "Host \\ Attr";

sub init()
{
	my $result = GetOptions ("sid=s" => \$SID,
		 );
    if ( ! defined ($SID) ) {
       ($sid)=get_sid_and_InstNr();
    } else {
       $sid=tolower($SID)
    }
}

init();
get_hana_attributes($sid);

#print_attr_host;
print_host_attr;
