#!/usr/bin/perl
#
# get_all_lnx_attributes
#
# license: GPL
# author:  fabian.herschel@suse.com
# date:    2014-05-13
# 
#
use POSIX;
use strict;

my $sid="";
my $table_title = "Host \\ Attr";
my %Name;
my %Host;

sub max { # thanks to http://www.perlunity.de/perl/forum/thread_018329.shtml
 my $a = shift;
 my $b = shift;
 return $a > $b ? $a : $b;
}

sub print_attr_host()
{
    my ($HKey, $AKey);
	printf "%-22s", "Attribute \\ Host";
	foreach $HKey (sort keys %Host) {
	   printf "%-16s ", $HKey;
	}
	printf "\n";

	printf "%s\n", "-" x 120 ;

	foreach $AKey (sort keys %Name) {
	   printf "%-22s", $AKey;
	   foreach $HKey (sort keys %Host) {
		   printf "%-16.16s ", $Host{$HKey} -> {$AKey};
		}

	   printf "\n";
	}
	return 0;
}

sub print_host_attr()
{
    my ($AKey, $HKey, $len, $line_len, $hclen);
    $hclen=$Name{_hosts}->{_length};
    $line_len=$hclen+1;
	printf "%-$hclen.${hclen}s ", "$table_title";
	foreach $AKey (sort keys %Name) {
       if ($AKey ne "_hosts") {
           $len = $Name{$AKey}->{_length};
           $line_len=$line_len+$len+1;
           printf "%-$len.${len}s ", $Name{$AKey}->{_title};
       }
	}
	printf "\n";
	printf "%s\n", "-" x $line_len ;
	foreach $HKey (sort keys %Host) {
	   printf "%-$hclen.${hclen}s ", $HKey;
	   foreach $AKey (sort keys %Name) {
           if ($AKey ne "_hosts") {
               $len = $Name{$AKey}->{_length};
               printf "%-$len.${len}s ", $Host{$HKey} -> {$AKey};
            }
        }
	   printf "\n";
	}
	return 0;
}

open ListInstances, "/usr/sap/hostctrl/exe/saphostctrl -function ListInstances|";
while (<ListInstances>) {
   # try to catch:  Inst Info : LNX - 42 - lv9041 - 740, patch 36, changelist 1444691
   chomp;
   if ( $_ =~ /:\s+([A-Z][A-Z0-9][A-Z0-9])\s+-/ ) {
      $sid=tolower("$1");
   }
}
close ListInstances;


open CIB, "cibadmin -Ql |";
while (<CIB>) {
   chomp;
   my ($host, $name, $value);
   my $found=0;
   if ( $_ =~ /nvpair.*name="(\w+_${sid}_\w+)"/ ) {
      $name=$1;
      # find attribute in forever and reboot store :)
      if ( $_ =~ /id="(status|nodes)-([a-zA-Z0-9\_\-]+)-/ ) {
         $host=$2;
      }
      if ( $_ =~ /value="([^"]+)"/ ) {
         $value=$1;
         $found=1;
      }
   }
   if ( $found == 1 ) {
       #
       # handle the hosts name and table-title
       #
       $Host{$host}->{$name}=${value};
       if ( defined ($Name{_hosts}->{_length})) {
          $Name{_hosts}->{_length} = max($Name{_hosts}->{_length}, length($host ));
       } else {
          $Name{_hosts}->{_length} = length($host );
       }
       $Name{_hosts}->{_length} = max($Name{_hosts}->{_length}, length( $table_title));
       #
       # now handle the attributes name and value
       #
       $Name{$name}->{$host}=${value};
       if ( defined ($Name{$name}->{_length})) {
          $Name{$name}->{_length} = max($Name{$name}->{_length}, length($value ));
       } else {
          $Name{$name}->{_length} = length($value );
       }
       if ( $name =~ /hana_${sid}_(.*)/ ) {
          $Name{$name}->{_title} =  $1;
       } else {
          $Name{$name}->{_title} = $name; 
       }
       $Name{$name}->{_length} = max($Name{$name}->{_length}, length( $Name{$name}->{_title}));
       # printf "%-8s %-20s %-30s\n", $1, $2, $3;
   }
}
close CIB;

#print_attr_host;
print_host_attr;
