#!/bin/sh

function ver_le {
    [  "$1" = "$(echo -e "$1\n$2" | sort -V | head -n1)" ]
}

function ver_lt {
    [ "$1" != "$2" ] && ver_le "$1" "$2" || return 1
}


function ver_ge {
    [  "$1" = "$(echo -e "$1\n$2" | sort -V | tail -n1)" ]   
    # alternatively:
    # ! ver_lt $1 $2
}

function ver_gt {
    [ "$1" != "$2" ] && ver_ge $1 $2 || return 1
}

function ver_ge_le {
    # compare: $2 <= $1 <= $3
    ver_ge $1 $2 && ver_ge $3 $1
}

function ver_gt_lt {
    # compare: $2 < $1 < $3
    ver_gt $1 $2 && ver_gt $3 $1
}

# version v1 LE v2              ==> ver_le v1 v2
# version v1 LE v2 LE v3        ==> ver_le v1 v2 && version v2 LE v3

function version() {
    if [ $# -eq 3 ]; then
        case "$2" in
            LE | le | "<=" ) ver_le $1 $3;;
            LT | lt | "<" ) ver_lt $1 $3;;
            GE | ge | ">=" ) ver_ge $1 $3;;
            GT | gt | ">" ) ver_gt $1 $3;;
            * ) return 1;
        esac
    elif [ $# -ge 5 ]; then
        version $1 $2 $3 && shift 2 && version $*
    else 
        return 1;
    fi
}

V1="1.0.090.9"
V2="1.0.110.0"
V3="1.0.110.3"

if version $V1 '<=' $V2; then echo "version $V1 '<=' $V2"; fi
if version $V2 '>=' $V1 '<' $V3 ; then echo "version $V2 '>=' $V1 '<' $V3"; fi

# test
if ver_le $V1 $V2; then echo "$V1 LE $V2"; fi
if ver_ge $V1 $V2; then echo "$V1 GE $V2"; fi
if ver_ge $V2 $V2; then echo "$V2 GE $V2"; fi
if ver_gt $V2 $V2; then echo "$V2 GT $V2"; fi
if ver_ge_le $V2 $V1 $V3; then echo "$V2 GE $V1 LE $V3"; fi
if ver_ge_le $V1 $V1 $V1; then echo "$V1 GE $V1 LE $V1"; fi
if ver_gt_lt $V1 $V1 $V1; then echo "$V1 GT $V1 LT $V1"; fi

echo "$V1 LE $V2: $($V1 ver_le $V2) $?"
