.\" Version: 1.2
.\"
.TH cs_ssh 1 "20 Nov 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
cs_ssh \- Cluster-aware ssh shell.
.PP
.\"
.SH SYNOPSIS
.\"
\fBcs_ssh\fR [ --help | --version ]
.PP
\fBcs_ssh\fR \fIOPTION\fR [ \fIPARAMETER\fR ] [ \fIOPTION\fR ... ]
.PP
.\"
.SH DESCRIPTION
.\"
cs_ssh is a cluster-aware ssh shell. It accepts a list of remote hosts to connect
to. The connection is made to the first host. If that hosts fails, cs_ssh connects
to the second host (and so on...). That allows to execute actions on a cluster while cluster nodes
are failing or get fenced.
.PP
.\"
.SH OPTIONS
.\"
.TP
--help
print help message and exit.
.TP
--version
print version and exit.
.TP
--hosts \fIHOST\fR [ \fIHOST\fR ... ]
remote hosts to connect to.
.TP
--command \fICOMMAND\fR
command to exceute remotely.
.TP
--user \fIUSER\fR
Linux user to use for ssh connection (default is current user).
.TP
--keyfile \fIFILE\fR
ssh private key file to use.
.TP
--quiet
suppress info messages.
.TP
--report_hostname
report hostname of succesful ssh connection.
.TP
--skip_hostcheck
skip check of known_hosts (use only in secure environments).
.PP
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.\"
TODO
.PP
.\"
.SH FILES
.\"
.TP
/usr/bin/cs_ssh
the program itself.
.TP
~/.ssh/id_ed25519
default ssh private key file.
.PP
.\"
.SH REQUIREMENTS
.\"
TODO
.PP
.\"
.SH BUGS
.\"
.\" In case of any problem, please use your favourite SAP support process to open
.\" a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-tester\fP(7) , \fBssh-keygen\fR(1) , \fBssh-copy-id\fR(1)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
