.\" Version: 1.2 
.\"
.TH SAPHanaSR-tests-angi-ScaleUp_on-fail-fence 7 "30 Sep 2024" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-angi-ScaleUp_on-fail-fence \- Functional tests for SAPHanaSR Scale-Up with immediate fencing.
.PP
.\"
.SH DESCRIPTION
.PP
Functional test are shipped for scale-up scenarios when configured for immediate
fencing. See manual page ocf_suse_SAPHanaController(7) and susChkSrv.py(7) for
the respective configuration details. This tests could be run
out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details. Details like
performed steps or expected behaviour of cluster and HANA are explained in
SAPHanaSR-tests-description(7).
.PP
Each test can be executed by running the command SAPHanaSR-testCluster with
appropriate parameters. See manual page SAPHanaSR-testCluster(8).
.PP
Overview on predefined functional tests specific for scale-up with immediate fencing:
.TP
\fBblock_sr_and_freeze_prim_fs\fP
Block HANA SR and freeze HANA FS on primary node, for SAPHanaFilesystem (ON_FAIL_ACTION=fence).
.TP
\fBfreeze_prim_fs_fencing\fP
Freeze HANA FS on primary master node, for SAPHanaFilesystem (ON_FAIL_ACTION=fence).
.TP
\fBkill_prim_indexserver_fencing\fP
Kill primary indexserver, for susChkSrv.py (action_on_lost=fence).
.TP
\fBkill_prim_inst_fencing\fP
Kill primary instance, for SAPHanaController (ON_FAIL_ACTION=fence).
.\" .TP
.\" \fBkill_prim_nic_fencing\fP
.\" Kill primary HANA network interface (IPAddr2 start on-fail=fence).
.TP
\fBkill_secn_indexserver_fencing\fP
Kill secondary indexserver, for susChkSrv.py (action_on_lost=fence).
.PP
More recommended tests, but not specific to immediate fencing, are listed in
manual page SAPHanaSR-tests-angi-ScaleUp(7).
.PP
.\"
.SH EXAMPLES
.PP
* List tests for SAPHanaSR-angi scale-up with immediate fencing scenarios
.PP
.RS 2
# ls /usr/share/SAPHanaSR-tester/json/angi-ScaleUp/*fenc*
.RE
.PP
.\"
.SH FILES
.\"
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleUp/
functional tests for SAPHanaSR-angi scale-up scenarios.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.\" .TP
.\" /usr/share/SAPHanaSR-tester/samples/runtests_angi-ScaleUp_progressive.txt
.\" test sequence example.    
.PP
.\"
.SH REQUIREMENTS
.\"
See the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-angi(7).
Further, HANA database and Linux cluster are configured almost according to the
SUSE setup guide for the scale-up performance-optimised  scenario.
In opposite to that guide, immediate fencing is configured.
See ocf_suse_SAPHanaController(7), susChkSrv.py(7) and
SAPHanaSR-alert-fencing(8).
Of course, HANA database and Linux cluster have certain requirements.
Please refer to the product documentation.
.PP
.\"
.SH BUGS
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-description_on-fail-fence\fP(7) ,
\fBSAPHanaSR-tests-description\fP(7) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-tests-angi-ScaleUp\fP(7) ,
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBocf_suse_SAPHanaController\fP(7) , \fBsusChkSrv.py\fP(7)
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2024 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
