.\" Version: 1.2.9
.\"
.TH SAPHanaSR-tests-classic-ScaleOut 7 "28 Jan 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-classic-ScaleOut \- Functional tests for SAPHanaSR-ScaleOut.
.PP
.\"
.SH DESCRIPTION
.PP
Functional test are shipped for the scale-out ERP scenario. This tests could
be run out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details. Details like
performed steps or expected behaviour of cluster and HANA are explained in
SAPHanaSR-tests-description(7).
.PP
Each test can be executed by running the command SAPHanaSR-testCluster with
appropriate parameters. See manual page SAPHanaSR-testCluster(8).
.PP
Overview on predefined functional tests for classical scale-out ERP:
.TP
\fBfree_log_area\fP
Free HANA log area on primary site.
.TP
\fBkill_prim_indexserver\fP
Kill primary master indexserver, for susChkSrv.py (action_on_lost=kill).
.TP
\fBkill_prim_inst\fP
Kill primary master instance.
.TP
\fBkill_prim_ipaddr\fP
Kill primary HANA´s IP address once.
.TP
\fBkill_prim_node\fP
Kill primary master node.
.TP
\fBkill_prim_saphostexec\fP
Kill primary master node´s saphostexec.
.TP
\fBkill_prim_worker_indexserver\fP
Kill primary worker indexserver, for susChkSrv.py (action_on_lost=kill).
.TP
\fBkill_prim_worker_inst\fP
Kill primary worker instance.
.TP
\fBkill_prim_worker_node\fP
Kill primary worker node.
.TP
\fBmaintenance_cluster_hana_running\fP
Maintenance procedure with stopping and restarting cluster, keep HANA running.
.TP
\fBmaintenance_cluster_turn_hana\fP
Maintenance procedure, manually turning HANA sites.
.TP
\fBnop\fP
No operation - check, wait and check again (stability check).
.TP
\fBstandby_prim_node\fP
Standby primary master node and online again.
.PP
Note: All tests are experimental.
.PP
.\"
.SH EXAMPLES
.PP
* List tests for SAPHanaSR-ScaleOut ERP scenarios
.PP
.RS 2
# ls /usr/share/SAPHanaSR-tester/json/classic-ScaleOut/
.RE
.PP
* Check for new SAPHanaSR-showAttr
.PP
.RS 2
/usr/bin/SAPHanaSR-showAttr --format=tester
.RE
.PP
.\"
.SH FILES
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleOut/
functional tests for SAPHanaSR-ScaleOut ERP scenarios.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.TP
/usr/bin/SAPHanaSR-showAttr
script SAPHanaSR-showAttr from SAPHanaSR-angi.
.PP
.\"
.SH REQUIREMENTS
.PP
.PP
* The package SAPHanaSR-tester-client is needed on the cluster nodes.
.PP
* See also the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR(7).
.PP
* Further, HANA database and Linux cluster are configured according to the SUSE
setup guide for the scale-out ERP style scenario (two nodes per site, no standby).
.PP
* Of course, HANA database and Linux cluster have certain requirements.
Please refer to the product documentation.
.\"
.SH BUGS
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-description\fP(7) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-tests-classic-ScaleUp\fP(7) ,
\fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBSAPHanaSR-tester-client\fP(7)
.PP
.\"
.SH AUTHORS
.PP
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2023-2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
