.\" Version: 1.2
.\"
.TH SAPHanaSR-tests-angi-DR-region 7 "07 Apr 2026" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
SAPHanaSR-tests-angi-DR-region \- Functional tests for SAPHanaSR-angi scale-up with DR HA for DR region.
.PP
.\"
.SH DESCRIPTION
.\"
Functional test are shipped for the scale-up with DR HA scenario. This tests
could be run out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details. Details like
performed steps or expected behaviour of cluster and HANA are explained in
SAPHanaSR-tests-description_angi-scale-up-DR-region(7).
.PP
Each test can be executed by running the command SAPHanaSR-testCluster with
appropriate parameters. See manual page SAPHanaSR-testCluster(8).
.PP
The tests are a sub-set of the SAPHanaSR-angi scale-up perf-opt progressive
tests. 
Main difference is that the DR region does not have an HANA primary. Instead of
the primary, one secondary (called third) is connected to the production region
and replicates to another secondary (called fourth).
So several CIB attributes are different. See manual page  SAPHanaSR_with_DR_HA(7).
.PP
Overview on predefined functional tests, specific for DR region:
.TP
\fBblock_fourth_node_network\fP
Block all network on fourth node.
.TP
\fBblock_manual_takeover\fP
Blocked manual takeover, for susTkOver.py.
.TP
\fBblock_sr\fP
Block HANA SR and check SFAIL attribute, unblock to recover, for susHanaSR.py.
.TP
\fBblock_third_node_network\fP
Block all network on third node.
.TP
\fBflup\fP
Like nop but very short sleep, just checking the test engine.
.\" .TP
.\" \fBfreeze_short_fourth_fs\fP
.\" Freeze HANA FS on fourth node, unfreeze to recover.
.\" .TP
.\" \fBfreeze_short_third_fs\fP
.\" Freeze HANA FS on third node, unfreeze to recover.
.TP
\fBkill_fourth_indexserver\fP
Kill fourth indexserver, for susChkSrv.py (action_on_lost=fence).
.TP
\fBkill_fourth_inst\fP
Kill fourth instance.
.TP
\fBkill_fourth_nameserver\fP
Kill fourth nameserver.
.TP
\fBkill_fourth_node\fP
Kill fourth node.
.TP
\fBkill_fourth_pacemakerd\fP
Kill fourth pacemakerd.
.TP
\fBkill_fourth_pacemkr-attrd\fP
Kill fourth pacemaker-attrd (PCMK_fail_fast=yes).
.TP
\fBkill_fourth_pacemkr-based\fP
Kill fourth pacemaker-based (PCMK_fail_fast=yes).
.TP
\fBkill_fourth_pacemkr-ctrld\fP
Kill fourth pacemaker-controld (PCMK_fail_fast=yes).
.TP
\fBkill_fourth_saphostexec\fP
Kill fourth saphostexec.
.TP
\fBkill_fourth_xsengine\fP
Kill fourth xsengine.
.TP
\fBkill_third_indexserver\fP
Kill third indexserver, for susChkSrv.py (action_on_lost=fence).
.TP
\fBkill_third_inst\fP
Kill third instance.
.TP
\fBkill_third_nameserver\fP
Kill third nameserver.
.TP
\fBkill_third_node\fP
Kill third node.
.TP
\fBkill_third_pacemakerd\fP
Kill third pacemakerd.
.TP
\fBkill_third_pacemkr-attrd\fP
Kill third pacemaker-attrd (PCMK_fail_fast=yes).
.TP
\fBkill_third_pacemkr-based\fP
Kill third pacemaker-based (PCMK_fail_fast=yes).
.TP
\fBkill_third_pacemkr-ctrld\fP
Kill third pacemaker-controld (PCMK_fail_fast=yes).
.TP
\fBkill_third_saphostexec\fP
Kill third saphostexec.
.TP
\fBkill_third_xsengine\fP
Kill third xsengine.
.TP
\fBmaintenance_cluster_hana_running\fP
Maintenance procedure with stopping and restarting cluster, keep HANA running.
.TP
\fBmaintenance_cluster_turn_hana\fB
Maintenance procedure, manually turning HANA sites.
.TP
\fBmaintenance_fourth_crmreport\fB
Maintenance procedure, calling crmreport on fourth node.
.TP
\fBmaintenance_fourth_supportconfig\fB
Maintenance procedure, calling supportconfig on fourth node.
.TP
\fBmaintenance_third_crmreport\fB
Maintenance procedure, calling crmreport on third node.
.TP
\fBmaintenance_third_supportconfig\fB
Maintenance procedure, calling supportconfig on third node.
.TP
\fBmaintenance_with_standby_nodes\fP
Maintenance procedure, standby+online third then standby+online fourth.
.TP
\fBnop\fP
No operation - check, wait and check again (stability check).
.TP
\fBone_stable_hour\fP
Check regulary for one hour that there is no failure, like nop.
.TP
\fBrestart_cluster_hana_running\fP
Stop and restart cluster, keep HANA running. Slightly differs from maintenance.
.TP
\fBrestart_cluster\fP
Stop and restart cluster and HANA.
.\" .TP
.\" \fBsplit_brain_prio\fP
.\" Network split-brain with priority fencing.
.TP
\fBstandby_fourth_node\fP
Set fourth node standby and online again.
.TP
\fBstandby_third_node\fP
Set third node standby and online again.
.PP
.\"
.SH EXAMPLES
.\"
* List tests for SAPHanaSR-angi scal-up scenarios.
.PP
.RS 2
# ls /usr/share/SAPHanaSR-tester/json/angi-ScaleU-DR-regionp/
.RE
.PP
.\"
.SH FILES
.\"
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleUp-DR-region/
functional tests for SAPHanaSR-angi scale-up with DR HA scenario for DR region.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.\" .TP
.\" /usr/share/SAPHanaSR-tester/samples/runtests_angi-ScaleUp-DR-region.txt
.\" test sequence example.  
.PP
.\"
.SH REQUIREMENTS
.\"
See the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-angi(7).
Further, HANA database and Linux cluster are configured according to the SUSE
setup guide for the scale-up performance-optimised scenario progressive variant
with DR HA scenario.
Of course, HANA database and Linux cluster have certain requirements.
Please refer to the product documentation.
.PP
.\"
.SH BUGS
.\"
.\" In case of any problem, please use your favourite SAP support process to open
.\" a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-description_angi-DR-region\fP(7) ,
\fBSAPHanaSR-tests-syntax\fP(5) , \fBSAPHanaSR-tests-angi-ScaleUp\fP(7) ,
\fBSAPHanaSR-tests-angi-ScaleUp_on-fail-fence\fP(7) ,
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR_with_DR_HA\fP(7) ,
\fBSAPHanaSR-showAttr\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
