.\" Version: 1.2.9
.\"
.TH SAPHanaSR-tests-angi-ScaleOut 7 "28 Jan 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-angi-ScaleOut \- Functional tests for SAPHanaSR Scale-Out.
.PP
.\"
.SH DESCRIPTION
.PP
Functional test are shipped for the scale-out ERP scenario. This tests could
be run out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details. Details like
performed steps or expected behaviour of cluster and HANA are explained in
SAPHanaSR-tests-description(7).
.PP
Each test can be executed by running the command SAPHanaSR-testCluster with
appropriate parameters. See manual page SAPHanaSR-testCluster(8).
.PP
Overview on predefined functional tests for scale-out ERP:
.TP
\fBnop\fP
No operation - check, wait and check again (stability check).
.PP
Note: All tests are experimental.
.PP
.\"
.SH EXAMPLES
.PP
* List tests for SAPHanaSR-ScaleOut ERP scenarios
.PP
.RS 2
# ls /usr/share/SAPHanaSR-tester/json/classic-ScaleOut/
.RE
.PP
* Check for new SAPHanaSR-showAttr
.PP
.RS 2
/usr/bin/SAPHanaSR-showAttr --format=tester
.RE
.PP
.PP
.\"
.SH FILES
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleOut/
functional tests for SAPHanaSR-ScaleOut ERP scenarios.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.TP
/usr/bin/SAPHanaSR-showAttr
script SAPHanaSR-showAttr from SAPHanaSR-angi.
.PP
.\"
.SH REQUIREMENTS
.PP
.PP
* The package SAPHanaSR-tester-client is needed on the cluster nodes.
.PP
* See also the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR(7).
.PP
* Further, HANA database and Linux cluster are configured according to the SUSE
setup guide for the scale-out ERP style scenario (two nodes per site, no standby).
.PP
* Of course, HANA database and Linux cluster have certain requirements.
Please refer to the product documentation.
.\"
.SH BUGS
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-description\fP(7) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-tests-classic-ScaleUp\fP(7) ,
\fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBSAPHanaSR-tester-client\fP(7)
.PP
.\"
.SH AUTHORS
.PP
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2023-2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
