.\" Version: 1.001
.\"
.TH SAPHanaSR-tests-basic-cluster 7 "20 Nov 2023" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-basic-cluster \- Testing SAPHanaSR clusters basics.
.PP
.\"
.SH DESCRIPTION
.\"
TODO
.PP
.\"
.SH EXAMPLES
.\"
.PP
\fB*\fR Checking systemd integration and OS settings for SAP HANA.
.PP
TODO
Basic OS features time and name resolution as well as HANA disk space are
checked. Integration of SAP hostagent and SAP HANA database with systemd are
checked. OS settings for HANA are checked.
Cluster nodes are "node1" and "node2", HANA SID is "HA1", instance
number is "85". Do this on all Linux cluster nodes.
See manual page SAPHanaSR_basic_cluster(7), SAPHanaSR-ScaleOut_basic_cluster(7)
and REQUIREMENTS section of SAPHanaSR-tester(7).
.PP
.RS 2
# chronyc sources | grep "\\^\\*"
. br
# grep -e node1 -e node2 /etc/hosts
.br
# df -h /hana/log/HA1 /hana/shared/HA1/HDB85/backup
.br
# systemd-cgls -u SAP.slice
.br
# saptune solution verify HANA
.RE
.PP
\fB*\fR Checking for errors in the system logs.
.PP
TODO
.PP
.RS 2
# cs_show_error_patterns | grep -v "=.0"
.RE
.PP
\fB*\fR Checking Linux cluster SBD basic setup.
.PP
For the basic Linux cluster components watchdog driver, SBD disks and service,
it is checked if they are configured and running. 
Do this on all Linux cluster nodes.
See manual page SAPHanaSR_basic_cluster(7), SAPHanaSR-ScaleOut_basic_cluster(7),
sbd(8), cs_show_sbd_devices(8) and REQUIREMENTS section below.
.PP
.RS 2
# grep -v "#" /etc/sysconfig/sbd
.br
# lsmod | grep -e wdt -e dog
.br
# lsof /dev/watchdog* | grep sbd
.br
# cs_show_sbd_devices
.br
# systemctl status sbd | grep -e Loaded -e Active
.RE
.PP
If the Linux cluster already has been configured, show the SBD resource.
Resource name is rsc_stonith_sbd.
.PP
.RS 2
# crm_mon -1r | grep stonith:external
.br
# crm configure show rsc_stonith_sbd
.RE
.PP
\fB*\fR Checking Linux cluster basics.
.PP
For the basic Linux cluster services corosync and pacemaker, it is checked if
they are activated and running. The registered STONITH device and CIB bootstarp
options are shown. 
See manual page SAPHanaSR_basic_cluster(7), SAPHanaSR-ScaleOut_basic_cluster(7),
stonith_admin(8) and REQUIREMENTS section of SAPHanaSR-tester(7).
.PP
.RS 2
# systemctl status corosync pacemaker | grep -e Loaded -e Active
.br
# stonith_admin --list-registered
.br
# crm cluster status
.br
# crm configure show cib-bootstrap-options
.br
# crm_mon -1rA
.RE
.PP
\fB*\fR Checking Linux cluster basic functionality.
.PP
For the basic Linux cluster components watchdog driver, sbd disks and service,
corosync service as well as pacemaker service, it is checked if they are
working. The cluster node "node2" will be fenced and should re-join
automatically. Hopefully this is the other one. Do this on all Linux cluster
nodes. See manual page crm(8).
.br
Note: Never do this on production systems. 
.PP
.RS 2
# crm cluster crash_test --kill-corosync
.br
# crm cluster crash_test --kill-pacemakerd
.br
# crm cluster crash_test --kill-sbd
.br
# crm cluster crash_test --fence-node node2
.RE
.PP
.\"
.SH FILES
.\"
TODO
.PP
.\"
.SH REQUIREMENTS
.\"
See the REQUIREMENTS section in SAPHanaSR-tester(7).
.PP
.\"
.SH BUGS
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-tester\fP(7) , 
\fBSAPHanaSR-tests-angi-ScaleUp\fP(7) , \fBSAPHanaSR-tests-angi-ScaleOut\fP(7) ,
\fBSAPHanaSR-angi\fP(7) ,
\fBcrm\fP(8) , \fBcrm_verify\fP(8) , \fBcs_show_error_patterns\fP(8) ,
\fBcs_sum_base_config\fP(8) , \fBcs_show_sbd_devices(8) , \fBsaptune() ,
.br
https://documentation.suse.com/sbp/sap/ ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://documentation.suse.com/sle-ha/ ,
.br
https://www.suse.com/releasenotes/
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2023 SUSE Linux GmbH, Germany.
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
