.\" Version: 1.001 
.\"
.TH SAPHanaSR-tests-angi-ScaleUp 7 "20 Nov 2023" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-angi-ScaleUp \- Functional tests for SAPHanaSR Scale-Up.
.PP
.\"
.SH DESCRIPTION
.PP
Functional test are shipped for scale-up scenarios. This tests could be run
out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details.

Entry point for all predefined tests is a clean and idle Linux cluster and a
clean HANA pair in sync. Same is true for the final state. 
See manual page SAPHanaSR_maintenance_examples(7) for detecting the correct
status and watching changes near real-time.
.PP
Predefined functional tests for scale-up overview:
.PP
\fBblock_manual_takeover\fP
.RS 2
Descr: blocked manual takeover, for susTkOver.py
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test: 
.br
Expect: Both nodes stay online.
Both HANA stay online.
Failed manual takeover attempt is logged in syslog and HANA tracefile.
SR stays SOK.
No takeover. No fencing.
.RE
.PP
\fBblock_sr\fP
.RS 2
Descr: block HANA SR and check SFAIL attribute; unblock to recover
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Both nodes stay online.
Both HANA stay online.
SR SFAIL and finally SOK.
No takeover. No fencing.
.RE
.PP
\fBblock_sr_and_freeze_prim_fs\fP
.RS 2
Descr: block HANA SR and freeze HANA FS on primary master node
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Both nodes stay online.
HANA primary is stopped and finally back online.
SR SFAIL and finally SOK.
No takeover. No fencing.
.RE
.PP
\fBflup\fP
.RS 2
Descr: like nop but very short sleep only - only for checking the test engine
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test: Wait and see.
.br
Expect: Cluster and HANA are up and running, all good.
.RE
.PP
\fBfree_log_area\fP
.RS 2
Descr: free HANA log area on primary site
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test: Free up HANA transaction log space and log backups.
.br
Expect: Cluster and HANA are up and running, all good.
.RE
.PP
\fBfreeze_prim_fs\fP
.RS 2
Descr: freeze HANA FS on primary master node
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect:
.RE
.PP
\fBkill_prim_indexserver\fP
.RS 2
Descr: Kill primary indexserver, for susChkService.py
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Primary node stays online.
HANA primary stopped and finally started as secondary.
SR SFAIL and finally SOK.
One takeover. No fencing (for action_on_lost=kill).
.RE
.PP
\fBkill_prim_inst\fP
.RS 2
Descr: Kill primary instance
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Primary node stays online.
HANA primary stopped and finally started as secondary.
SR SFAIL and finally SOK.
One takeover. No fencing.
.RE
.PP
\fBkill_prim_node\fP
.RS 2
Descr: Kill primary node
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Primary node stopped and finally started as secondary.
HANA primary stopped and finally started as secondary.
SR SFAIL and finally SOK.
One takeover. One fencing.
.RE
.PP
\fBkill_secn_indexserver\fP
.RS 2
Descr: Kill secondary indexserver
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: HANA secondary stopped and finally online.
HANA primary stays online.
SR SFAIL and finally SOK.
No takeover. No fencing (for action_on_lost=kill).
.RE
.PP
\fBkill_secn_inst\fP
.RS 2
Descr: Kill secondary instance
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: HANA secondary stopped and finally online.
HANA primary stays online.
SR SFAIL and finally SOK.
No takeover. No fencing.
.RE
.PP
\fBkill_secn_node\fP
.RS 2
Descr: Kill secondary node
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Secondary node fenced and finally online.
HANA primary stays online.
SR SFAIL and finally SOK.
No takeover. One fencing.
.RE
.PP
\fBmaintenance_cluster_turn_hana\fP
.RS 2
Descr: maintenance procedure, manually turning HANA sites
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Both nodes stay online.
HANA primary stopped and finally started as secondary.
HANA secondary becomes finally primary by manual takeover.
SR SFAIL and finally SOK. 
One takeover. No fencing.
.RE
.PP
\fBmaintenance_with_standby_nodes\fP
.RS 2
Descr: standby+online secondary then standby+online primary
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect:  Both nodes stay online.
HANA primary stopped and finally started as secondary.
HANA secondary becomes finally primary.
SR SFAIL and finally SOK.
One takeover. No fencing.
.RE
.PP
\fBnop\fP
.RS 2
Descr: no operation - check, wait and check again (stability check)
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test: Wait and see.
.br
Expect: Cluster and HANA are up and running, all good.
.RE
.PP
\fBrestart_cluster_hana_running\fP
.RS 2
Descr:
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test: 
.br
Expect: Both nodes stay online.

No takeover. No fencing.
.RE
.PP
\fBrestart_cluster\fP
.RS 2
Descr:
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Both nodes stay online.

No takeover. No fencing.
.RE
.PP
\fBrestart_cluster_turn_hana\fP
.RS 2
Descr:
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Both nodes stay online.

One takeover. No fencing.
.RE
.PP
\fBsplit_brain_prio\fP
.RS 2
Descr: Network split-brain with priority fencing
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Secondary node fenced and finally online.
Primary node stays online.
HANA primary stays online.
SR SFAIL and finally SOK.
No takeover. One fencing.
.RE
.PP
\fBstandby_primary_node\fP
.RS 2
Descr: Set primary node standby and online again
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Both nodes aty online.
Primary node standby and finally back online.
HANA primary stopped and finally started as secondary.
HANA secondary finally primary by takeover.
SR SFAIL and finally SOK.
One takeover. No fencing.
.RE
.PP
\fBstandby_secondary_node\fP
.RS 2
Descr: Set secondary node standby and online again
.br
Prereq: Cluster and HANA are up and running, all good.
.br
Test:
.br
Expect: Secondary node standby and finally online.
HANA primary stays online.
HANA secondary stopped and finally started.
SR SFAIL and finally SOK. No takeover. No fencing.
.RE
.PP
.\"
.SH EXAMPLES
.PP
.\"
.SH FILES
.\"
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleUp/
functional tests for SAPHanaSR-angi scale-up scenarios.
.TP
/usr/bin/test_*
shell scripts for un-easy tasks on the cluster nodes.
.PP
.\"
.SH REQUIREMENTS
.\"
See the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-angi(7).
.PP
.\"
.SH BUGS
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-angi-ScaleOut\fP(7) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-showAttr\fP(8)
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2023 SUSE Linux GmbH, Germany.
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
