.\" Version: 1.2
.\"
.TH SAPHanaSR-testCluster-output 5 "15 Feb 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-testCluster-output \- SAPHanaSR-testCluster output files and formats.
.PP
.\"
.SH DESCRIPTION
.PP
SAPHanaSR-tester is a suite of tools for automating functional tests of SAP HANA
system replication HA clusters.
.PP
SAPHanaSR-testCluster TODO
.br
syslog style lines
.br
JSON structure
.br
TODO output to file or to stdout 
.PP
.\"
.SH SYNTAX
.PP
\fB* JSON structured output\fP
.PP
TODO
.PP
\fB* Syslog style lined output\fP
.PP
TODO
Each line consists of five fields:
.PP
\fIYY-MM-DD hh:mm:ss\fP [\fIPID\fP] \fITYPE\fP: \fItext\fP
.PP
The fields are 
.TP
\fIYY-MM-DD hh:mm:ss\fP
date and time
.TP
PID
process ID of the test, should be unique for a while  
.TP
TYPE
[ ACTION | ERROR | INIT | PARAM | PROC | STATUS | TEST | TOPO ], see below 
.TP
text
whatsoever message text
.PP
Each completed test starts and ends with a line containing type "TEST". All lines for that test show the same PID.
.\" TODO meaning of type  
.PP
.\"
.SH EXAMPLES
.PP
.\" 2025-02-15 12:49:21 [47624] STATUS:   step final40 checked in 33 loop(s)
.\"
.PP
\fB*\fP Show all passed tests from logfiles.
.PP
.RS 2
# grep TEST.*PASSED *.log
.RE
.PP
\fB*\fP Show all entries for the test with PID 2212.
.PP
.RS 2
# grep "\\[2212\\]" *.log
.RE
.PP
.\"
.SH BUGS
.PP
The SAPHanaSR-tester is under development. Syntax and formats are subject to
change.
.br
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-testCluster\fP(8) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-tester\fP(7)
.PP
.\"
.SH AUTHORS
.PP
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
