.\" Version: 1.2
.\"
.TH SAPHanaSR-tests-angi-XSA 7 "06 Dec 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
SAPHanaSR-tests-angi-XSA \- Functional tests for SAPHanaSR-angi scale-out XSA.
.PP
.\"
.SH DESCRIPTION
.\"
Functional test are shipped for the scale-out XSA scenario. This tests could
be run out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details. Details like
performed steps or expected behaviour of cluster and HANA are explained in
SAPHanaSR-tests-description_angi-XSA(7).
.PP
Each test can be executed by running the command SAPHanaSR-testCluster with
appropriate parameters. See manual page SAPHanaSR-testCluster(8).
.PP
In general the tests are mostly similar to the scale-out ERP scenario, progressive
variant. Unlike the scale-out ERP scenario, for scale-out XSA the worker roles are
showing "slave:slave:none:none".
.PP
Overview on predefined functional tests, specific for scale-out XSA:
.TP
\fBkill_prim_worker_xscontrl\fP
Kill primary worker xscontroller, for XSA.
.TP
\fBkill_prim_worker_xsexecagnt\fP
Kill primary worker xsexecagent, for XSA.
.TP
\fBkill_prim_worker_xsuaasrvr\fP
Kill primary worker xsuaaserver, for XSA.
.TP
\fBkill_secn_worker_xscontrl\fP
Kill secondary worker xscontroller, for XSA.
.TP
\fBkill_secn_worker_xsexecagnt\fP
Kill primary worker xsexecagent, for XSA.
.TP
\fBkill_secn_worker_xsuaasrvr\fP
Kill primary worker xsuaaserver, for XSA.
.TP
\fBrestart_cluster_turn_hana_xsa\fP
Stop cluster and HANA, takeover HANA, start cluster.
.PP
Overview on predefined functional tests, not specific for scale-out XSA:
.TP
\fBblock_manual_takeover\fP
Blocked manual takeover, for susTkOver.py.
.TP
\fBblock_prim_site_network\fP
Block all network at primary site nodes.
.TP
\fBblock_secn_site_network\fP
Block all network at secondary site nodes.
.TP
\fBblock_sr\fP
Block HANA SR between master nodes and check SFAIL attribute, unblock to recover, for susHanaSR.py.
.\" .TP
.\" \fBblock_sr_and_freeze_prim_master_nfs\fP
.\" Block HANA SR and freeze HANA FS on primary master node, for SAPHanaFilesystem (ON_FAIL_ACTION=fence).
.TP
\fBcleanup_cib\fP
Clean up failures, constraints, maintenance, etc.
.TP
\fBflup\fP
Like nop but very short sleep, just checking the test engine.
.TP
\fBfree_log_area\fP
Free HANA log area on primary site.
.TP
\fBfreeze_prim_master_nfs_fencing_alert\fP
Freeze HANA NFS on primary master node, for SAPHanaFilesystem (ON_FAIL_ACTION=fence) and SAPHanaSR-alert-fencing.
.TP
\fBfreeze_prim_site_nfs_fencing_alert\fP
Freeze HANA NFS on primary site, for SAPHanaFilesystem (ON_FAIL_ACTION=fence) and SAPHanaSR-alert-fencing.
.TP
\fBfreeze_secn_site_nfs\fP
Freeze HANA NFS on secondary site.
.TP
\fBkill_prim_indexserver_fencing_alert\fP
Kill primary master indexserver, for susChkSrv.py (action_on_lost=fence) and SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_inst_fencing_alert\fP
Kill primary master instance, for SAPHanaController (ON_FAIL_ACTION=fence) and SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_ipaddr\fP
Kill primary HANA´s IP address once.
.TP
\fBkill_prim_node_fencing_alert\fP
Kill primary master node, for SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_pacemakerd\fP
Kill primary master node´s pacemakerd.
.TP
\fBkill_prim_pacemkr-attrd_fencing_alert\fP
Kill primary master pacemaker-attrd, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_pacemkr-based_fencing_alert\fP
Kill primary master pacemaker-based, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_pacemkr-ctrld_fencing_alert\fP
Kill primary master pacemaker-controld, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_saphostexec\fP
Kill primary master node´s saphostexec.
.TP
\fBkill_prim_worker_ipaddr\fP
Kill primary HANA worker XSA IP address once.
.TP
\fBkill_prim_worker_inst_fencing_alert\fP
Kill primary worker instance, for SAPHanaController (ON_FAIL_ACTION=fence) and SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_worker_node_fencing_alert\fP
Kill primary worker node, for SAPHanaSR-alert-fencing.
.TP
\fBkill_prim_worker_pacemakerd\fP
Kill primary worker node´s pacemakerd.
.TP
\fBkill_secn_indexserver_fencing_alert\fP
Kill secondary master indexserver, for susChkSrv.py (action_on_lost=fence) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_node_fencing_alert\fP
Kill secondary master node, for SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_pacemakerd\fP
Kill secondary master node´s pacemakerd.
.TP
\fBkill_secn_pacemkr-attrd_fencing_alert\fP
Kill secondary master pacemaker-attrd, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_pacemkr-based_fencing_alert\fP
Kill secondary master pacemaker-based, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_pacemkr-ctrld_fencing_alert\fP
Kill secondary master pacemaker-conntrold, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_worker_node_fencing_alert\fP
Kill secondary worker node, for SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_worker_pacemakerd\fP
Kill secondary worker node´s pacemakerd.
.TP
\fBkill_secn_worker_pacemkr-attrd_fencing_alert\fP
Kill secondary worker node´s pacemaker-attrd, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_worker_pacemkr-based_fencing_alert\fP
Kill secondary worker pacemaker-based, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_worker_pacemkr-ctrld_fencing_alert\fP
Kill secondary worker node´s pacemaker-controld, for pacemakerd (PCMK_fail_fast=yes) and SAPHanaSR-alert-fencing.
.TP
\fBkill_secn_xsengine\fP
Kill secondary master xsengine.
.TP
\fBmaintenance_cluster_hana_running\fP
Maintenance procedure with stopping and restarting cluster, keep HANA running.
.TP
\fBmaintenance_cluster_turn_hana\fP
Maintenance procedure, manually turning HANA sites.
.TP
\fBmaintenance_prim_crmreport\fP
Maintenance procedure, calling crm report on primary master node.
.TP
\fBmaintenance_prim_supportconfig\fP
Maintenance procedure, calling supportconfig on primary master node.
.TP
\fBnop\fP
No operation - check, wait and check again (stability check).
.TP
\fBone_stable_hour\fP
Check regulary for one hour that there is no failure, like nop.
.TP
\fBrestart_cluster\fP
Stop and restart cluster and HANA
.TP
\fBrestart_cluster_hana_running\fP
Stop and restart cluster, keep HANA running. Slightly differs from maintenance.
.PP
.\"
.SH EXAMPLES
.\"
* List tests for SAPHanaSR-angi scale-out XSA scenarios
.PP
.RS 2
# ls /usr/share/SAPHanaSR-tester/json/angi-ScaleOut-XSA/
.RE
.PP
.\"
.SH FILES
.\"
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleOut-XSA/
functional tests for SAPHanaSR-angi scale-out XSA scenario.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.PP
.\"
.SH REQUIREMENTS
.\"
See the REQUIREMENTS section in 
SAPHanaSR-tester(7) and SAPHanaSR-angi(7).
.\"
.SH BUGS
.\"
.\" In case of any problem, please use your favourite SAP support process to open
.\" a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-description\fP(7) ,
\fBSAPHanaSR-tests-description_on-fail-fence\fP(7) ,
\fBSAPHanaSR-tests-syntax\fP(5) , \fBSAPHanaSR-tests-angi-ScaleOut\fP(7) ,
\fBSAPHanaSR-ScaleOut-XSA\fP(7) , \fBSAPHanaSR-showAttr\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2025-2026 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
