.\" Version: 1.001
.\"
.TH SAPHanaSR-tests-syntax 5 "20 Nov 2023" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-syntax \- Syntax for SAPHanaSR test cases and properties.
.PP
.\"
.SH DESCRIPTION
.\"
SAPHanaSR-tester is a suite of tools for automating functional tests of SAP HANA
system replication HA clusters.



The test cases are defined in dedicated files. Each test is separated into
steps.
For each step there is an expectation for SAPHanaSR attributes, which need to
match. Additionally each step defines the 'next' step and an optional action
to be triggered if the step status has been reached (all expectations match).
See section SYNTAX below for comparators and other details.

For tests involving complex actions on the cluster nodes, predefined shell
scripts are executed remotely.
.\" TODO state machine.

See manual pages SAPHanaSR-tests-angi-ScaleUp(7) and
SAPHanaSR-tests-angi-ScaleOut(7) for predefined test cases.
.PP
.\"
.SH SYNTAX
.\"
The test cases are defined in JSON files. Each test case is described in one
file. It also can reference to defaults.json for common status definitions.
.PP
\fB*\fP Test step status
.PP
Each step contains an expectation for SAPHanaSR attributes, which need to
match. The step status are:
.TP
globalUp
both sites are up and in sync
.TP
globalDown
not yet implemented
.TP
pHostUp
host p (expected to be primary before the test starts) is up  
.TP
pSiteUp
site p is up  
.TP
sSiteUp
site s (expected to be secondary before the test starts) is up  
.TP
sHostUp
host s is up  
.TP
pHostDown
host p is down 
.TP
pSiteDown
site p is down 
.TP
sSiteDown
site s is down 
.TP
sHostDown
host s is down 
.PP
Note: Prefixes "s" and "p" are statically indicating geographical sites, as
seen at the beginning of a test. If a takeover happens during that test, the
final secondary site might be prefixed "p".
.PP
Each test step status is described by one or more conditions. Each condition
is described by one comparision. This conditions are combined by logical "AND".
Each comparision consists of one CIB SAPHanaSR attribute name, one comparator
and one value or regular expression. This comparator and expression could
contain logical "OR". A status with two conditions looks like this:
.PP
"\fR<test_step_status>\fP": [
.br
               "\fR<parameter_name> <comparator> <value>" ,
.br
               "\fR<parameter_name> <comparator> <value>"
.br
           ]
.PP
A set of comparators is implemented. Some take integers, some take regular
expression. In addition the "None" TODO. 
.\" saphana_sr_test.py
.\" re.search("(.*) (==|!=|>|>=|<|<=|~|!~|>~|is) (.*)", single_check)
.TP
==
equal, integer
.TP
!=
not equal, integer
.TP
>=
greater or equal, integer
.TP
<=
less or equal, interger
.TP
>
greater, integer
.TP
<
less
.TP
>~
greater or like, first field integer and second field regular expression ( <integer>:<regular_expression> )
.TP
~
like, regular expression
.TP
!~
not like, regular expression
.TP
is
TODO, the string "None"
.PP
\fB*\fP Test step actions
.PP
TODO
.TP
post
action after step, [ bmt | cleanup | spn | ssn | osn | script <script> | kill_... ] 
.RE
See also the EXAMPLES section in manual pages SAPHanaSR-tests-angi-ScaleUp(7)
and SAPHanaSR-tests-angi-ScaleOut(7).
.PP
\fB*\fP Test system properties
.PP
TODO statical values, decribing the test system.

See also example below.

\fB*\fP Test results

See manual page SAPHanaSR-testCluster(8) for TODO
.PP
.\"
.SH EXAMPLES
.\"
TODO
.PP
.\"
.SH FILES
.\"
/usr/share/SAPHanaSR-tester/json/angi-ScaleUp/
functional tests for SAPHanaSR-angi scale-up scenarios.
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleOut/
functional tests for SAPHanaSR-angi scale-out ERP scenarios, without HANA host auto-autofailover.
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleOut-BW/
functional tests for SAPHanaSR-angi scale-out BW scenarios, with HANA host auto-autofailover. Not yet implemented.
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleUp/
not yet implemented.
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleOut/
not yet implemented.
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleOut-BW/
not yet implemented.
.TP
$PWD/.test_properties
auto-generated properties file for called shell scripts. No need to touch.
.TP
/usr/bin/SAPHanaSR-testCluster
program to run a predefined testcase.
.PP
.\"
.SH REQUIREMENTS
.\"
See the REQUIREMENTS section in SAPHanaSR-tester(7).
.PP
.\"
.SH BUGS
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-tester\fP(7) ,  \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-angi-ScaleUp\fP(7) , \fBSAPHanaSR-tests-angi-ScaleOut\fP(7) ,
\fBSAPHanaSR-showAttr\fP(8) ,
.br
https://documentation.suse.com/sbp/sap/ ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://www.suse.com/releasenotes/
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2023 SUSE Linux GmbH, Germany.
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
