.\" Version: 1.2
.\"
.TH SAPHanaSR-testOutQuery 8 "06 Jan 2026" "" "SAPHanaSR-angi"
.\"
.SH NAME
.\"
SAPHanaSR-testOutQuery \- TODO SAPHanaSR-runTest JSON output file.
.PP
.\"
.SH SYNOPSIS
.\"
\fBSAPHanaSR-testOutQuery\fR [ --help | --version ]
.br
\fBSAPHanaSR-testOutQuery\fR --file \fIFILE\fR
.PP
.\"
.SH DESCRIPTION
.\"
TODO
.PP
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.\"
.PP
.\"
.TP
/usr/bin/SAPHanaSR-testOutQuery
the program itself.
.PP
.\"
.SH REQUIREMENTS
.\"
See REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-tests-syntax(5).
.PP
.\"
.SH BUGS
.\"
.\" In case of any problem, please use your favourite SAP support process to open
.\" a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBSAPHanaSR-tester\fP(7), \fBSAPHanaSR-runTest\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
