.\" Version: 1.2
.\"
.TH SAPHanaSR-tests-angi-ScaleOut 7 "19 Feb 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-tests-angi-ScaleOut \- Functional tests for SAPHanaSR Scale-Out.
.PP
.\"
.SH DESCRIPTION
.PP
Functional test are shipped for the scale-out ERP scenario. This tests could
be run out-of-the-box. The test cases are defined in dedicated files.
See manual page SAPHanaSR-tests-syntax(5) for syntax details. Details like
performed steps or expected behaviour of cluster and HANA are explained in
SAPHanaSR-tests-description(7).
.PP
Each test can be executed by running the command SAPHanaSR-testCluster with
appropriate parameters. See manual page SAPHanaSR-testCluster(8).
.PP
Overview on predefined functional tests for scale-out ERP:
.TP
\fBblock_manual_takeover\fP
Blocked manual takeover, for susTkOver.py.
.\" .TP
.\" \fBblock_prim_site_network\fP
.\" Block all network at primary site nodes.
.TP
\fBblock_secn_site_network\fP
Block all network at secondary site nodes.
.TP
\fBblock_sr\fP
Block HANA SR between master nodes and check SFAIL attribute, unblock to recover, for susHanaSR.py.
.TP
\fBflup\fP
Like nop but very short sleep, just checking the test engine.
.TP
\fBfree_log_area\fP
Free HANA log area on primary site.
.TP
\fBfreeze_secn_site_nfs\fP
Freeze HANA NFS on secondary site.
.TP
\fBkill_prim_indexserver\fP
Kill primary master indexserver, for susChkSrv.py (action_on_lost=kill).
.TP
\fBkill_prim_inst\fP
Kill primary master instance.
.TP
\fBkill_prim_ipaddr\fP
Kill primary HANA´s IP address once.
.\" .TP
.\" \fBkill_prim_nameserver\fP
.\" Kill primary master nameserver.
.TP
\fBkill_prim_node\fP
Kill primary master node.
.TP
\fBkill_prim_pacemakerd\fP
Kill primary master node´s pacemakerd.
.\" .TP
.\" \fBkill_prim_pacemkr-attrd\fP
.\" Kill primary master node´s pacemaker-attrd (PCMK_fail_fast=no).
.\" .TP
.\" \fBkill_prim_pacemkr-ctrld\fP
.\" Kill primary master node´s pacemaker-controld (PCMK_fail_fast=no).
.TP
\fBkill_prim_saphostexec\fP
Kill primary master node´s saphostexec.
.\" .TP
.\" \fBkill_prim_site_nodes\fP
.\" Kill primary site nodes.
.TP
\fBkill_prim_worker_indexserver\fP
Kill primary worker indexserver, for susChkSrv.py (action_on_lost=kill).
.TP
\fBkill_prim_worker_inst\fP
Kill primary worker instance.
.TP
\fBkill_prim_worker_node\fP
Kill primary worker node.
.TP
\fBkill_prim_worker_pacemakerd\fP
Kill primary worker node´s pacemakerd.
.\" .TP
.\" \fBkill_prim_pacemkr-attrd\fP
.\" Kill primary master node´s pacemaker-attrd (PCMK_fail_fast=no).
.\" .TP
.\" \fBkill_prim_worker_pacemkr-ctrld\fP
.\" Kill primary worker node´s pacemaker-controld (PCMK_fail_fast=no).
.\" .TP
.\" \fBkill_prim_xsengine\fP
.\" Kill primary master xsengine.
.TP
\fBkill_secn_indexserver\fP
Kill secondary master indexserver, for susChkSrv.py (action_on_lost=kill).
.TP
\fBkill_secn_inst\fP
Kill secondary master instance.
.TP
\fBkill_secn_nameserver\fP
Kill secondary master nameserver.
.TP
\fBkill_secn_node\fP
Kill secondary master node.
.TP
\fBkill_secn_pacemakerd\fP
Kill secondary master node´s pacemakerd.
.\" .TP
.\" \fBkill_secn_pacemkr-attrd\fP
.\" Kill secondary master node´s pacemaker-attrd (PCMK_fail_fast=no).
.\" .TP
.\" \fBkill_secn_pacemkr-ctrld\fP
.\" Kill secondary master node´s pacemaker-controld (PCMK_fail_fast=no).
.TP
\fBkill_secn_site_nodes\fP
Kill all nodes at secondary site.
.TP
\fBkill_secn_worker_inst\fP
Kill secondary worker instance.
.TP
\fBkill_secn_worker_node\fP
Kill secondary worker node.
.TP
\fBkill_secn_worker_pacemakerd\fP
Kill secondary worker node´s pacemakerd.
.TP
\fBkill_secn_worker_pacemkr-ctrld\fP
Kill secondary worker node´s pacemaker-controld (PCMK_fail_fast=no).
.\" .TP
.\" \fBkill_secn_xsengine\fP
.\" Kill secondary master xsengine.
.TP
\fBmaintenance_cluster_bootstrap\fP
Maintenance procedure, initially configuring cluster resources. Not yet implemented.
.TP
\fBmaintenance_cluster_hana_running\fP
Maintenance procedure with stopping and restarting cluster, keep HANA running.
.TP
\fBmaintenance_cluster_turn_hana\fP
Maintenance procedure, manually turning HANA sites.
.TP
\fBmaintenance_with_standby_nodes\fP
Maintenance procedure, standby+online secondary then standby+online primary. Not yet implemented.
.TP
\fBnop\fP
No operation - check, wait and check again (stability check).
.TP
\fBone_stable_hour\fP
Check regulary for one hour that there is no failure, like nop.
.\" .TP
.\" \fBregister_prim_cold_hana\fP
.\" Stop cluster, do manual takeover, leave former primary down and unregistered, start cluster.
.TP
\fBrestart_cluster\fP
Stop and restart cluster and HANA
.TP
\fBrestart_cluster_hana_running\fP
Stop and restart cluster, keep HANA running. Slightly differs from maintenance.
.TP
\fBrestart_cluster_turn_hana\fP
Stop cluster and HANA, takeover HANA, start cluster.
.TP
\fBstandby_prim_node\fP
Standby primary master node and online again.
.TP
\fBstandby_secn_node\fP
Standby secondary master node and online again.
.TP
\fBstandby_secn_worker_node\fP
Standby secondary worker node and online again.
.PP
.\"
.SH EXAMPLES
.PP
* List tests for SAPHanaSR-angi scale-out ERP scenarios
.PP
.RS 2
# ls /usr/share/SAPHanaSR-tester/json/angi-ScaleOut/
.RE
.PP
.\"
.SH FILES
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleOut/
functional tests for SAPHanaSR-angi scale-out ERP scenarios.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.\" .TP
.\" /usr/share/SAPHanaSR-tester/samples/runtests_angi-ScaleOut_progressive.txt
.\" test sequence example.    
.PP
.\"
.SH REQUIREMENTS
.PP
See the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-angi(7).
Further, HANA database and Linux cluster are configured according to the SUSE
setup guide for the scale-out ERP style scenario (two nodes per site, no standby).
No immediate fencing is configured, except for the SAPHanaFilesystem RA.
Of course, HANA database and Linux cluster have certain requirements.
Please refer to the product documentation.
.\"
.SH BUGS
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-testCluster\fP(8) ,
\fBSAPHanaSR-tests-description\fP(7) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-tests-angi-ScaleOut_on-fail-fence\fP(7) ,
\fBSAPHanaSR-tests-angi-ScaleUp\fP(7) ,
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-showAttr\fP(8)
.PP
.\"
.SH AUTHORS
.PP
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2023-2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
