.\" Version: 1.2
.\"
.TH SAPHanaSR-testCluster 8 "15 Feb 2025" "" "SAPHanaSR-angi"
.\"
.SH NAME
SAPHanaSR-testCluster \- Run functional tests for SAPHanaSR clusters.
.PP
.\"
.SH SYNOPSIS
.PP
\fBSAPHanaSR-testCluster\fR [ --help | --version ]
.br
\fBSAPHanaSR-testCluster\fR \fIOPTION\fR [ \fIOPTION\fR ... ]
.PP
.\"
.SH DESCRIPTION
.PP
SAPHanaSR-testCluster is a tool to run one of the predefined test cases on a
given test cluster. For that purpose it is called with options specifying the
test case and the properties of the cluster to be tested.
SAPHanaSR-testCluster can be seen as low-level command to be used in scripts
and test automation frameworks.
.PP
.\"
.SH OPTIONS
.TP
--help
print help message and exit.
.TP
--defaultsFile \fIFILE\fP
path to defaults file.
.TP
--dumpFailures
print failed checks per loop, see also --jsonOut.
.TP
--debug
print and log debug messages.
.TP
--jsonOut \fIFILE\fP
JSON file to write detailled test results, see also SAPHanaSR-testCluster-output(5).
.TP
--logFile \fIFILE\fP
path to log file, see also SAPHanaSR-testCluster-output(5).
.TP
--password \fIPASSWORD\fP
remote root user´s password (for debugging only).
.TP
--printTestProperties
print test properties and exit, see also SAPHanaSR-tests-syntax(5).
.TP
--properties \fIFILE\fP
path to poperties file.
.TP
--remoteNode \fINODE\fP [ \fINODE\fP ... ]
cluster nodes to use for ssh connection, must not be last option in cmdline.
.TP
--repeat \fIINTEGER\fP
how often to repeat the test.
.TP
--simulate
only simulate, do not call actions.
.TP
--testFile \fIFILE\fP
path to testcase description file.
.TP
--version
print version and exit.
.PP
.\"
.SH RETURN CODES
.PP
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.PP
\fB*\fR Running a very basic functional test.
.PP
The functional test "nop" is performed on the Linux cluster defined in
properties_q42.json, nodes are node1 and node2.
A dedicated working directory and logfile for this test is used.
See also manual page SAPHanaSR-tester(7), SAPHanaSR-tests-syntax(5),
SAPHanaSR-tests-angi-ScaleUp(7) and SAPHanaSR-tests-description(7).
.PP
.RS 2
# mkdir ~/test_nop; cd ~/test_nop
.br
# export TROOT=/usr/share/SAPHanaSR-tester/json/angi-ScaleUp/
.br
# SAPHanaSR-testCluster \\
.br
--testFile $TROOT/nop.json \\
.br
--remoteNodes node1 node2 \\
.br
--defaultsFile $TROOT/defaults.json \\
.br
--properties ~/properties_q42.json \\
.br
--logFile test.log
.RE
.PP
\fB*\fR Showing failed tests from logfile.
.PP
Logfile is test.log, shown are time, test ID, test case.
.PP
.RS 2
# grep "TEST:.*FAILED" test.log | awk '{print $2,$3,$5}'
.RE
.PP
\fB*\fR Showing details for a single test.
.PP
Test ID is 8585, logfile is test.log, debug output is omitted.
.PP
.RS 2
# grep "\\[8585\\]" test.log | grep -v "DEBUG:"
.RE
.PP
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-testCluster
the program itself.
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleUp/
functional tests for SAPHanaSR-angi scale-up scenarios.
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleOut/
functional tests for SAPHanaSR-angi scale-out ERP scenarios, without HANA host auto-failover.
.TP
/usr/share/SAPHanaSR-tester/json/angi-ScaleOut-BW/
functional tests for SAPHanaSR-angi scale-out BW scenarios, with HANA host auto-failover. Not yet implemented.
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleUp/
functional tests for SAPHanaSR classic scale-up scenarios.
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleOut/
functional tests for SAPHanaSR-ScaleOut ERP scenarios, without HANA host auto-failover.
.TP
/usr/share/SAPHanaSR-tester/json/classic-ScaleOut-BW/
not yet implemented.
.TP
$PWD/.test_properties
auto-generated properties file for called shell scripts. No need to touch.
.TP
/usr/bin/SAPHanaSR-showAttr
script SAPHanaSR-showAttr from SAPHanaSR-angi.
.TP
/usr/bin/sct_test_*
shell scripts for un-easy tasks on the cluster nodes.
.PP
.\"
.SH REQUIREMENTS
.PP
See the REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-angi(7).
Of course, HANA database and Linux cluster have certain requirements.
Please refer to the product documentation.
.PP
.\"
.SH BUGS
.PP
* The shell scripts for triggering failures are not enclosed by timeouts.
.PP
* The shell scripts for triggering failures almost do not log.
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-tester-output\fP(5) ,
\fBSAPHanaSR-tests-syntax\fP(5) , \fBSAPHanaSR-tests-description\fP(7) ,
\fBSAPHanaSR-tests-classic-ScaleUp\fP(7) , \fBSAPHanaSR-tests-classic-ScaleOut\fP(7) ,
\fBSAPHanaSR-tests-angi-ScaleUp\fP(7) , \fBSAPHanaSR-tests-angi-ScaleOut\fP(7) ,
\fBSAPHanaSR-angi\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBcrm_mon\fP(8) , \fBcrm\fP(8) , \fBcs_clusterstate\fP(8) , \fBcs_show_cluster_actions\fP(8)
.PP
.\"
.SH AUTHORS
.PP
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2023-2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
