.\" Version: 1.2
.\"
.TH SAPHanaSR-checkJson 8 "26 Nov 2024" "" "SAPHanaSR-angi"
.\" TODO SAPHanaSR-testJson ?
.\"
.SH NAME
SAPHanaSR-checkJson \- Check syntax of SAPHanaSR-tester JSON file.
.PP
.\"
.SH SYNOPSIS
.PP
\fBSAPHanaSR-checkJson\fR [ --help | --version ]
.br
\fBSAPHanaSR-checkJson\fR --file \fIFILE\fR [ --quiet ]
.PP
.\"
.SH DESCRIPTION
.PP
SAPHanaSR-checkJson is a tool for checking SAPHanaSR-tester JSON files for
formally correct syntax.
.PP
.\"
.SH OPTIONS
.TP
--help
print help message and exit.
.TP
--file \fIFILE\fP
specify the JSON file to check.
.TP
--quiet
do not output JSON data on success.
.TP
--version
print version and exit.
.PP
.\"
.SH RETURN CODES
.PP
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.PP
.\"
.SH EXAMPLES
.PP
\fB*\fP List predefined testfiles for SAPHanaSR-angi scale-up setups.
.PP
.RS 2 
# ls /usr/share/SAPHanaSR-tester/json/angi-ScaleUp/*.json
.RE
.PP
\fB*\fP Check one of the predefined files.
.PP
.RS 2 
# SAPHanaSR-checkJson --file /usr/share/SAPHanaSR-tester/json/angi-ScaleUp/maintenance_cluster_hana_running.json
.RE
.PP
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-checkJson
the program itself.
.TP
/usr/share/SAPHanaSR-tester/json/
path to directories with predefined functional tests.
.PP
.\"
.SH REQUIREMENTS
.PP
See REQUIREMENTS section in SAPHanaSR-tester(7) and SAPHanaSR-tests-syntax(5).
.PP
.\"
.SH BUGS
.PP
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.PP
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-tests-syntax\fP(5) ,
\fBSAPHanaSR-tests-classic-ScaleUp\fP(7) , \fBSAPHanaSR-tests-classic-ScaleOut\fP(7) ,
\fBSAPHanaSR-tests-angi-ScaleUp\fP(7) , \fBSAPHanaSR-tests-angi-ScaleOut\fP(7)
.PP
.\"
.SH AUTHORS
.PP
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.PP
(c) 2023-2025 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
