.\" Version: 1.001
.\"
.TH SAPHanaSR-tester-client 7 "27 Jan 2024" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-tester \- Functional testing for SAPHanaSR clusters.
.PP
.\"
.DESCRIPTION
.\"
SAPHanaSR-tester-client is a package to allow using SAPHanaSR-tester for 
classical SAPHanaSR and SAPHanaSR-ScaleOut HA cluster.

.B SAPHanaSR-tester is shipped as technology preview. 

The package


.SH EXAMPLES
.\"
\fB*\fR Installing SAPHanaSR-tester.
.PP
.PP
.RS 2
# zypper in SAPHanaSR-tester
.RE
.PP
.PP
.\"
.SH FILES
.\"
.TP
/usr/bin/SAPHanaSR-shoaAttr

.PP
.\"
.SH REQUIREMENTS
.\"
.SH BUGS
The SAPHanaSR-tester-client is under development. Syntax and formats are
subject to change.
.br
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-tests-classic-ScaleUp\fP(7) ,
\fBSAPHanaSR-showAttr\fP(8)
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2023 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
