.\" Version: 1.001
.\"
.TH SAPHanaSR-tester-client 7 "27 Jan 2024" "" "SAPHanaSR"
.\"
.SH NAME
SAPHanaSR-tester-client \- Client for functional testing SAPHanaSR clusters.
.PP
.\"
.DESCRIPTION
.\"
SAPHanaSR-tester-client is a package that allows to use SAPHanaSR-tester for 
testing classical SAPHanaSR and SAPHanaSR-ScaleOut HA clusters.

.B SAPHanaSR-tester is shipped as technology preview. 

The package provides a specific version of SAPHanaSR-shwoAttr, compatible to
SAPHanaSR-angi and SAPHanaSR-tester.
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fR Checking the SAPHanaSR-showAttr.
.PP
The specific SAPHanaSR-showAttr is called to show the output format needed for
testing. See manual page SAPHanaSR-showAttr(8) from package SAPHanaSR-angi for
details.
.PP
.RS 2
# /usr/bin/SAPHanaSR-showAttr --format=tester
.RE
.PP
.\"
.SH FILES
.\"
.TP
/usr/bin/SAPHanaSR-showAttr
specific SAPHanaSR-showAttr, compatible to SAPHanaSR-angi and SAPHanaSR-tester
.PP
.\"
.SH REQUIREMENTS
See SAPHanaSR-tester(7), SAPHanaSR-tests-classic-ScaleUp(7) and SAPHanaSR(7).
.\"
.SH BUGS
The SAPHanaSR-tester-client is under development. Syntax and formats are
subject to change.
.br
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE.
Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBSAPHanaSR-tester\fP(7) , \fBSAPHanaSR-tests-classic-ScaleUp\fP(7) ,
\fBSAPHanaSR-showAttr\fP(8), \fBSAPHanaSR\fP(7)
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
(c) 2024 SUSE LLC
.br
The package SAPHanaSR-tester comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
