#!/bin/bash
#
# SAPHanaSR-alert
# Author:       Lars Pinne Fabian Herschel, June 2024
# Support:      linux@sap.com
# License:      GNU General Public License (GPL)
# Copyright:    (c) 2024 SUSE LLC
# 2024-06-12-13:14
#
# crm configure alert nodes-1 "/usr/bin/SAPHanaSR-alert" select nodes
# crm configure alert fencing-1 "/usr/bin/SAPHanaSR-alert" select fencing
#

logger_tag="SAPHanaSR-alert"

# ON_FAIL_ACTION="${OCF_RESKEY_ON_FAIL_ACTION:-proceed}"
CRM_alert_recipient="${CRM_alert_recipient:-/dev/null}"
crm_alert_kind="${CRM_alert_kind:-manual call}"
crm_alert_node="${CRM_alert_node:-$HOSTNAME}"
crm_alert_desc="${CRM_alert_desc:-no description provided}"
/usr/bin/logger -t "$logger_tag" "AH: begin event '$crm_alert_kind'"
cache_file="/run/crm/SAPHanaSR_site_cache"

function process_fencing()
{
	# SAPHanaSR_site_cache has format (each line) host:site_name
	# figure out fenced site
	
	if [[ -e "$cache_file" ]]; then
		fenced_site_name=$(awk -F: '$1 == host { print $2 }' host="${crm_alert_node}" "$cache_file")
		local_site_name=$(awk -F: '$1 == host { print $2 }' host="${HOSTNAME}" "$cache_file")
		if [[ "$local_site_name" != "" && "$fenced_site_name" == "$local_site_name" ]]; then
			/usr/bin/logger -t "$logger_tag" "DEC: FENCE ($fenced_site_name == $local_site_name)"
			/usr/sbin/crm --force node fence "${HOSTNAME}"; rc="$?"
			if [[ "$rc" != "0" ]]; then
				/usr/bin/logger -t "$logger_tag" "/usr/sbin/crm --force node fence ${HOSTNAME}; rc=$rc"
			fi
		else
			/usr/bin/logger -t "$logger_tag" "DEC: NO FENCE ($fenced_site_name != $local_site_name)"
		fi
	else
	    /usr/bin/logger -t "$logger_tag" "DEC: NO FENCE (no cache)"
	fi
}

case "$crm_alert_kind" in
    node|nodes)
        msg="Node '${crm_alert_node}' is now '${crm_alert_desc}'"
        /usr/bin/logger -t "$logger_tag" "$msg"
        ;;
    fencing)
        msg="Fencing for '${crm_alert_node}': ${crm_alert_desc}"
        /usr/bin/logger -t "$logger_tag" "$msg"
        process_fencing
        ;;
    *)
	    msg="Unhandled '$crm_alert_kind' alert (${crm_alert_desc})"
        /usr/bin/logger -t "$logger_tag" "$msg"
        ;;
esac
/usr/bin/logger -t "$logger_tag" "AH: end event '$crm_alert_kind'"
#
